### DISCUSSION TITLE
Custom Sensor: Today's Solar Consumption [for Deye SUN Hybrid inverter]

### DISCUSSION THREAD

**Discussion by PV-Joe** [davidrapan/ha-solarman#108] [Show and tell]
### This sensor calculates the solar energy consumed directly in the household for the current day by taking the total production and subtracting the energy that was either stored in the battery or exported to the grid. It matches the value calculated by the Energy Dashboard in Home Assistant also known as self-used solar energy.

It can be added to the "deye_sg04lp3.yaml" using the following sensors is as follows:
(please note that the Modbus registers used here can only be applied to Deye SUN Hybrid inverters but you can easily customize the Modbus registers to match with other models or brands).

**Modbus registers entityID's and calculation:**

    [0x0211] = sensor.solarman_today_production -
    [0x0202] = sensor.solarman_today_battery_charge -
    [0x0209] = sensor.solarman_today_energy_export
    ______________________________________________________
             = Today Solar Consumption
              (new entityID: today_solar_consumption)

**YAML Sensor to be added to the "deye_sg04lp3.yaml" or "custom_components.yaml":**
(It is recommended to use it in a "custom_components.yaml" otherwise it will be overwritten with the next Solarman update)

```
  #############################################
  # Custom Sensors (for deye_sg04lp3.yaml) #
  #############################################

      # Calculates today's production consumed directly from the solar panels
      # Formula: sensor.solarman_today_production - sensor.solarman_today_battery_charge - sensor.solarman_today_energy_export
      - name: Today Solar Consumption
        alt: Daily Solar Consumption
        friendly_name: Today's Solar Consumption
        description: Energy production consumed directly from the solar panels
        update_interval: 30
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        rule: 1
        digits: 1
        registers: [0x0211, 0x0202, 0x0209]
        sensors:
          - scale: 0.1
            registers: [0x0211]
          - operator: subtract
            scale: 0.1
            registers: [0x0202]
          - operator: subtract
            scale: 0.1
            registers: [0x0209]
``` 

Energy Dashboard of Home Assistant (orange = self-used energy):
![grafik](https://github.com/user-attachments/assets/be08b8fe-658f-4e83-8d7a-9ad5e9c0a07a)
