### DISCUSSION TITLE
Massaging battery parameters to use with the Energy Dashboard

### DISCUSSION THREAD

**Discussion by PaulOckenden** [davidrapan/ha-solarman#126] [Ideas]
I use an ME3000SP with the solarman_wifikit.yaml definition file.

I tried to add my batteries to HA's energy dashboard, but couldn't because it expects to see in and out values in kWh (evergy), but the output from the ME3000SP is a single charge/discharge instantaneous reading in kW (power). So I had to massage that data into the right format to get it to work.

In case anyone else wants to try, this is how I did it. This is based on stuff I found out there on the Internet, but which didn't work, so I had to make loads of changes. All of this goes into configuration.yaml, by the way.

Firstly, I split the charge/discharge into separate in and out entities using templates:

```
template:
  - sensor: 
      - name: "batt1 out"
        state: >
          {% if states.sensor.battery1_battery_charge_discharge_power.state | float <= 0 %}
            {{ 0 - states.sensor.battery1_battery_charge_discharge_power.state | float }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: kW
        device_class: power
        icon: mdi:battery-minus
      - name: "batt1 in" 
        state: >
          {% if states.sensor.battery1_battery_charge_discharge_power.state | float  > 0 %}
            {{ states.sensor.battery1_battery_charge_discharge_power.state | float }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: kW
        device_class: power
        icon: mdi:battery-plus
```
You'll see I use batt1 in the code - that's because I have two battery systems. batt2 have essentially the same code duplicated.
 
You will need to replace battery1_battery_charge_discharge_power with whatever the charge/discharge parameter is called in your system. I think that by default it's solarman_battery_charge_discharge_power.

The next thing I do is use the built in integral facility to sum the kW feed into kWh data:
 
```
sensor:
   - platform: integration
    source: sensor.batt1_in
    name: batt1_in_integration
    round: 3
    method: left
  - platform: integration
    source: sensor.batt1_out
    name: batt1_out_integration
    round: 3
    method: left

```

You may well have an existing sensor: section, if so just add this to the end of that. 

Finally, I use the built-in utility meter facility to reset the data on a daily basis:

```
utility_meter:
  batt1_in_integration_daily:
    source: sensor.batt1_in_integration
    cycle: daily
  batt1_out_integration_daily:
    source: sensor.batt1_out_integration
    cycle: daily

```

After this, I'm able to use batt1_in_integration_daily and batt1_out_integration_daily to populate the battery fields in the energy dashboard. It won't show correct data until the following day. 

I hope someone else finds that useful!
