### DISCUSSION TITLE
HYD 6000 EP - configurable battery charging from grid

### DISCUSSION THREAD

**Discussion by wixaw** [davidrapan/ha-solarman#185] [Q&A]
Hello,

I would like to be able to control my "HYD 6000 EP" in order to program the battery to charge from the grid overnight whenever I want.

Will it be possible to do this with your plugin in the future, or will I have to use RS232 ?

Thank you in advance.

Best regards.

**Comment by davidrapan** [comment]
Hi @wixaw, of course it should be possible. The only thing needed is to know the right registers in the modbus which controls it.

**Comment by wixaw** [comment]
so if I understood correctly I don't have modbus, because I don't have RS232 yet, and so I would like to be able to make the commands in IP

**Comment by davidrapan** [comment]
No no no, this integration also uses modbus but through solarman stick logger. It just provides the connection to the modbus of the inverter. 😉

**Comment by wixaw** [comment]
oh wow, would you have an idea to give me to tell me how to interact?
maybe a code that configures something on the inverter that could inspire me, because currently I see in your plugin only reading
Thank you very much 🙏

**Reply by davidrapan** [reply]
In Developer tools there are ACTIONS where integration exposes services. For reading and writing registers and that can be used to find the correct registers for setting up charging from the grid. If you find them let me know and I will add it directly to the profile as configurable entity.

**Reply by wixaw** [reply]
ok thanks ! 
I have an excel document with all the commands (half in Chinese xD), I'll try to find it and get back to you

**Reply by davidrapan** [reply]
Here is file with list of some registers which could also be used as starting point: [registriesMap.csv](https://github.com/user-attachments/files/17178845/registriesMap.csv)

The procedure is easy, just change the charging button on the inverter and look for changed registers the value should be 0 for off and 1 for on probably.

**Reply by wixaw** [reply]
Re,
I don't know how to use your csv, I haven't ventured to tinker with pysolarmanv5

Here is where I stand with my initial tests:

I found this document ( sheet 2 : register ) which is ultra-comprehensive, and even though it is marked SOFAR G3, my HYD6000EP seems to match for the values I have modified.  
[SOFAR-G3 External Modbus Protocol-EN-V1.10 (20220622).xlsx](https://github.com/user-attachments/files/17179297/SOFAR-G3.External.Modbus.Protocol-EN-V1.10.20220622.xlsx)


Via "Solarman: Read Holding Registers (Modbus Function Code 3)"
By reading 4368, I get the value changing from 0 to 4 when I change it via the inverter.

If I set it to 1, it is not the correct name "Time-of-use electricity price model" but "mode temps utilisaton."
It works, as I can set it to charge from 00h to 06h from Monday to Friday.

However, writing via "Solarman: Write Holding Register (Modbus Function Code 6)" does not work.
If I want to set 4368 to 1 or 4, I get "Failed to execute action solarman.write_holding_register. V5 frame does not contain a valid Modbus RTU frame."

**Reply by davidrapan** [reply]
> Re,
I don't know how to use your csv, I haven't ventured to tinker with pysolarmanv5

It's not about that library at all. **The csv is just list of registers for you to try out**... 

For writing you have to use `Modbus function Code 16`.

**Reply by wixaw** [reply]
That work ! Thanks you so much

i do 2 automation :

Start load: 
```
alias: ifDemainRougeChargeBatterie
description: ""
trigger:
  - platform: time
    at: "22:10:00"
condition:
  - condition: state
    entity_id: sensor.rte_tempo_prochaine_couleur
    attribute: attribution
    state: Rouge
action:
  - action: solarman.write_multiple_holding_registers
    metadata: {}
    data:
      wait_for_attempts: 5
      device: 3c2eb32cdc5e79ef5f8a6bf1a47979b3
      register: 4368
      values: 1
  - action: notify.notify
    metadata: {}
    data:
      message: "EDFTempo: Lancement de la charge batterie"
mode: single
```

Stop load
```
alias: SiRougeEtBatteriePleine
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.onduleur_battery
    above: 99
condition:
  - condition: state
    entity_id: sensor.rte_tempo_couleur_actuelle
    state: Rouge
  - condition: state
    entity_id: sensor.rte_tempo_prochaine_couleur
    state: Rouge
action:
  - action: solarman.write_multiple_holding_registers
    data:
      wait_for_attempts: 5
      device: 3c2eb32cdc5e79ef5f8a6bf1a47979b3
      register: 4368
      values: 0
  - action: notify.notify
    metadata: {}
    data:
      message: "EDFTempo: Batterie pleine, arret de la charge"
mode: single

```
If I find a better solution I will say it here
