### DISCUSSION TITLE
Hinen inverter profile

### DISCUSSION THREAD

**Discussion by nathan026** [davidrapan/ha-solarman#198] [Q&A]
Is there any documentation on getting started with creating a new inverter profile? I have a Hinen H5000 inverter and have tried all of the current profiles without any luck.

**Comment by davidrapan** [comment]
Hi @nathan026, if you don't have modbus rtu protocol from the manufacturer the simplest proly would be to create your custom profile (empty for the start) in `inverter_definitions/custom/your_name.yaml` (but not sure if there are proper cheks to be able to load it completely empty, though, but you will see)

And then use bult-in services trough Developer Tools > ACTIONS > Solarman Read 0x3 and 0x4 and start probing registers.

But I would try to ask your manufacturer if they are not maybe willing to provide you with documentation on the modbus protocol.

😉

**Reply by nathan026** [reply]
Thanks, I started probing the registers but wow, that would have been a nightmare! I managed to get in contact with them and have the protocol now. I'll see what I can do with it.

[Hinen Inverter Modbus RTU Protocol V1.62    20240927.xlsx](https://github.com/user-attachments/files/17336677/Inverter.Modbus.RTU.Protocol.V1.62.20240927.xlsx)

**Reply by nathan026** [reply]
Is it better to clone and modify an existing profile or to create a new one from scratch?

**Reply by davidrapan** [reply]
I would say it's better to take some of the deye profiles as an example. 😉 And just replace register numbers.

**Reply by thiagofigueiro** [reply]
@nathan026, did you get anywhere with your profile? I also have a H5000 and am looking to monitor/control it locally via modbus.

**Comment by thiagofigueiro** [comment]
@davidrapan, I'm building the configuration for the Hinen H5000 based on the documentation attached to this issue.

The `uint16` registers are being decoded successfully, but I am having some trouble with the `uint32` registers.

For example, `EChargeTotal H` and `EChargeTotal L` are registers `[278, 279]` and defined as a `uint32` with a scale of 0.1kWh.

Reading them, I get `0` for `H` and `3460` for `L`.

<img width="687" alt="image" src="https://github.com/user-attachments/assets/9622d43e-eb25-4d5e-bfcc-d9f0ffecb393" />

The value, according to the Solarman site is 346kWh, which matches the values above.

However, when decoding with rule 1 or 3, I get a very high number:

<img width="312" alt="image" src="https://github.com/user-attachments/assets/4b271687-aa95-4bfb-b1f5-4b82ebdb9a1f" />

If I pick only the L register, I get 120kWh:

<img width="311" alt="image" src="https://github.com/user-attachments/assets/c4d8c5b3-6525-4c3f-9c37-27e2336ec7e7" />


This is the configuration:

```yaml
      - name: "Total Battery Charge"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 1
        registers: [278,279]
          #        registers: [279]
        icon: "mdi:battery-plus"
        validation:
          min: 0.1
```

Do you have any advice for me to get the same value as the actions query is reporting?

Thanks in advance!

**Reply by davidrapan** [reply]
> However, when decoding with rule 1 or 3, I get a very high number:

You need to change the order in registers list. It's low then high bytes.

**Reply by thiagofigueiro** [reply]
OOOOooooh! that makes sense. Thank you so much.

Interestingly enough, it still shows the same value

```
      - name: "Total Battery Charge 2"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 3
        registers: [279,278]
        icon: "mdi:battery-plus"
        validation:
          min: 0.1

      - name: "Total Battery Charge"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 3
        registers: [278,279]
        icon: "mdi:battery-plus"
        validation:
          min: 0.1
```

<img width="328" alt="image" src="https://github.com/user-attachments/assets/898a132d-7991-4e03-8b49-cae25cfb37ec" />

Am I missing something really silly?

**Reply by thiagofigueiro** [reply]
Looks like it's working. I'll send a PR with the configuration file once I finish checking values and adding some more sensors.

<img width="314" alt="image" src="https://github.com/user-attachments/assets/7a9277fe-1511-4e58-b087-dc064d0f8d6b" />

**Reply by davidrapan** [reply]
It proly just needed a reload or restart. 😉

**Reply by CountParadox** [reply]
Hi guys, did you need to enable anything in the inverter to connect ? What port did you use ?

**Reply by djuricivan** [reply]
> Hi guys, did you need to enable anything in the inverter to connect ? What port did you use ?

Did you figure out which port to use? I'm not sure how to determine that.
Are you using a WiFi logger or WiFi module from Hinen?

**Reply by CountParadox** [reply]
> > Hi guys, did you need to enable anything in the inverter to connect ? What port did you use ?
> 
> Did you figure out which port to use? I'm not sure how to determine that.
> Are you using a WiFi logger or WiFi module from Hinen?

I haven't figured it out yet. ![Screenshot_20260206_085107_Hinen Solar.png](https://github.com/user-attachments/assets/105d5a9a-b292-469c-b141-30632ad2bcd3)

**Reply by djuricivan** [reply]
> > > Hi guys, did you need to enable anything in the inverter to connect ? What port did you use ?
> > 
> > 
> > Did you figure out which port to use? I'm not sure how to determine that.
> > Are you using a WiFi logger or WiFi module from Hinen?
> 
> I haven't figured it out yet. 

from what I see on your screenshot, it could be that you're using a WiFi logger, and not a WiFi module from Hinen - yes, there's a difference that I also learned about today.
<img width="1600" height="406" alt="image" src="https://github.com/user-attachments/assets/f7048218-f5c5-4315-99ac-0485218c6aa1" />

According to their manual, only by using a WiFi module you can also use Solarman app / this integration, so it's worth checking out.

**Reply by CountParadox** [reply]
But I am using the solarman app!

**Reply by djuricivan** [reply]
> But I am using the solarman app!

Don't know mate, this is what's written on their webpage:
<img width="619" height="667" alt="image" src="https://github.com/user-attachments/assets/64e9d99e-2790-40c4-a91f-0fbf8114c848" />

Maybe you _do_ have a Wifi module, and not Wifi logger? But you need to check that for yourself.

**Comment by thiagofigueiro** [comment]
Meanwhile, here's what I've got so far

```yaml
parameters:
 - group: solar
   items:
    - name: "Total Production"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [253,252]
      icon: 'mdi:solar-power'

    - name: "Total Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 0.1
      rule: 1
      registers: [2,1]
      icon: 'mdi:home-lightning-bolt'

    - name: "Total Production PV1"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [259,258]
      icon: 'mdi:solar-panel'
 - group: Battery
   items:
    - name: "Total Battery Charge"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [279,278]
      icon: 'mdi:battery-plus'

    - name: "Total Battery Discharge"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [283,282]
      icon: 'mdi:battery-minus'

    - name: "Battery Discharge Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [103,102]
      icon: 'mdi:battery'

    - name: "Battery Charge Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [105,104]
      icon: 'mdi:battery'

    - name: "Battery SOC"
      class: "battery"
      state_class: "measurement"
      uom: "%"
      scale: 1
      rule: 1
      registers: [128]
      icon: 'mdi:battery'

    - name: "Battery Priority"
      scale: 1
      rule: 1
      registers: [125]
      isstr: true
      icon: 'mdi:fuel-cell'
      lookup:
      -  key: 0
         value: "Load priority"
      -  key: 1
         value: "Battery priority"
      -  key: 2
         value: "Grid priority"

 - group: Inverter
   items:
    - name: "Running Status"
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0]
      isstr: true
      lookup:
      -  key: 0
         value: "Stand-by"
      -  key: 1
         value: "Grid-connected"
      -  key: 2
         value: "Off-grid"
      -  key: 3
         value: "FAULT"
      -  key: 4
         value: "Update mode"
      -  key: 5
         value: "Charging"
      -  key: 6
         value: "Discharging"
      -  key: 7
         value: "Bypass"
      icon: 'mdi:home-lightning-bolt'

    - name: "Backflow power limit"
      class: "power"
      state_class: "measurement"
      uom: "%"
      rule: 1
      registers: [75]
      icon: 'mdi:home-lightning-bolt'

    - name: "Load-first charge rate"
      class: "power"
      state_class: "measurement"
      uom: "%"
      rule: 1
      registers: [136]
      icon: 'mdi:battery'
```

**Reply by davidrapan** [reply]
Great!

Just make sure you are using common entity naming as I can see few deviations. 😉

Examples:
* `Battery` instead of `Battery SOC` (Note: `class: battery` can be used only once)
* `Device State` instead of `Running Status`
* Just `Power` instead of `Total Power` (but only if it refers to the device output power, if it's for grid, load or else it has to be stated but as a rule don't use `Total` with context of a sum power, etc.)
* `Total Production 1` instead of `Total Production PV1`

Edit2: You can look into deye_p3.yaml how are entity names structured.

Edit: `isstr: true` is not needed and do not include empty properties such as `class: ""` or default `scale: 1` (`rule: 1` is needed though). Descriptions which contains lookup should have `class: "Enum"` if they are not defined as `platform: select`.

**Reply by thiagofigueiro** [reply]
Yes, thanks for the feedback.

I'll start with `deye_hybrid.yaml`, find the matching registers, but keep the names and the icons.

We can work-out any kinks in the MR review.

Thanks again for your help with this. I'm quite happy using modbus instead of the cloud solarman api, which only updates every 5 minutes and depends on the Internet.

**Reply by kibukiri** [reply]
Thanks @thiagofigueiro and @davidrapan for creating and updating the solarman stick for Hinen as I just recently had a Hinen 5000 installed.

I copied the profie @thiagofigueiro posted above but somehow the Battery SOC is showing a constant 12,000%. When I query the register (128 according to the docs) it correctly shows 100% at the time of query. Any pointers on where I may be going wrong here?

Thanks

**Reply by nathan026** [reply]
@kibukiri Did you sort this issue out? It looks like it's using Holding Register (Function Code 3) instead of the Input Register.

@davidrapan what's the best way to solve this? I tried adding `input_type: input` but it didn't help

```yaml
- group: Battery
    items:
      - name: "Battery"
        class: "battery"
        state_class: "measurement"
        uom: "%"
        rule: 1
        input_type: input
        registers: [128]
```

**Reply by nathan026** [reply]
I found a solution, using code: 4 works.

I found it in this coment: https://github.com/davidrapan/ha-solarman/discussions/242#discussioncomment-11116549

```yaml
  - group: Battery
    items:
      - name: "Battery"
        class: "battery"
        state_class: "measurement"
        uom: "%"
        rule: 1
        code: 4
        registers: [128]
```

**Reply by nathan026** [reply]
Here's a working config, still missing a heap of entities.

```yaml
default:
  update_interval: 10

parameters:
  - group: Info
    items:
      - name: "Device State"
        class: "enum"
        rule: 1
        code: 4
        registers: [0]
        icon: "mdi:state-machine"
        isstr: true
        lookup:
          - key: 0x00
            value: "Stand-by"
          - key: 0x01
            value: "Grid-connected"
          - key: 0x02
            value: "Off-grid"
          - key: 0x03
            value: "FAULT"
          - key: 0x04
            value: "Update mode"
          - key: 0x05
            value: "Charging"
          - key: 0x06
            value: "Discharging"
          - key: 0x07
            value: "Bypass"

  - group: PV
    update_interval: 5
    items:
      - name: "PV Power"
        alt: DC Power
        description: Combined power of all inputs
        class: "power"
        state_class: "measurement"
        uom: "W"
        rule: 1
        digits: 0
        scale: 0.1
        code: 4
        registers: [2, 1]
        #sensors:
        #  - registers: [2]
        #  - registers: [1]
        icon: "mdi:solar-power-variant"

  - group: Battery
    items:
      - name: "Battery"
        class: "battery"
        state_class: "measurement"
        uom: "%"
        rule: 1
        code: 4
        registers: [128]

      - name: "Battery State"
        description: Determines battery state from battery power by +-50 W
        class: "enum"
        rule: 0
        #rule: 1 # Not working???
        #registers: [0x00BD]
        #lookup: - key: 0 value: "charging" - key: 1 value: "idle" - key: 2 value: "discharging"
        options: ["charging", "idle", "discharging"]
        icon: "mdi:battery"

      - name: "Battery Voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        code: 4
        registers: [127]

      - name: "Battery Power"
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 0.1
        rule: 1
        code: 4
        registers: [103, 102]

  #- group: Grid
  #  items:
  #- name: "Grid Power"
  #  class: "power"
  #  state_class: "measurement"
  #  uom: "W"
  #  rule: 2
  #  code: 4
  #  registers: []
  #  icon: "mdi:transmission-tower"

  - group: Load
    items:
      - name: "Load Power"
        class: "power"
        state_class: "measurement"
        uom: "W"
        rule: 1
        scale: 0.1
        code: 4
        registers: [77, 76]
````
