### DISCUSSION TITLE
New custom dashboard

### DISCUSSION THREAD

**Discussion by wixaw** [davidrapan/ha-solarman#204] [Ideas]
Hello,

I have a new proposal for the dashboard

![image](https://github.com/user-attachments/assets/45487388-9820-4c19-b9e7-e0139397049c)

My goal is to replicate the content of the "energy ease" application as much as possible like this : 

![Screenshot_2024-10-09-14-36-50-84_98017e3a2abffd7e59900584e8d2ecdd (1)](https://github.com/user-attachments/assets/c3687856-2821-442d-ba98-841208433755)

The only thing I can't do is navigation by date 😢 
The real downside of this plugin is the loading time, but it might be related to my environment. I need to migrate from my Raspberry Pi to a server.

Work with my HYD 6000 EP 

```
type: custom:apexcharts-card
view_layout:
  grid-area: solar
header:
  show: true
  standard_format: true
  show_states: true
  colorize_states: true
apex_config:
  grid:
    show: true
  tooltip:
    enabled: true
    shared: true
    followCursor: true
  xaxis:
    axisTicks:
      show: false
    axisBorder:
      show: false
  chart:
    height: 550
    zoom:
      type: x
      enabled: true
      autoScaleYaxis: false
    toolbar:
      show: true
      autoSelected: zoom
cache: true
graph_span: 1d
span:
  start: day
all_series_config:
  float_precision: 2
  curve: smooth
  type: area
  opacity: 0.5
  yaxis_id: normal
  unit: kW
  show:
    legend_value: true
    in_header: false
  group_by:
    func: avg
    duration: 5m
  stroke_width: 2
  extend_to: false
  transform: return x/1000;
update_delay: 3s
update_interval: 1min
series:
  - entity: sensor.inverter_pv1_power
    name: Production
    color: '#44be61'
  - entity: sensor.inverter_load_power
    name: Consumption
    color: '#ec7967'
  - entity: sensor.inverter_grid_power
    name: Grid
    color: '#b364c0'
  - entity: sensor.inverter_battery_power
    name: Battery
    color: '#54c1bf'
yaxis:
  - id: normal
    show: true
```
