### DISCUSSION TITLE
Read Multiple Bit in register?

### DISCUSSION THREAD

**Discussion by murik85** [davidrapan/ha-solarman#206] [Q&A]
Is there any way to read the register bits to display inverter errors? Register U32.

Example:  register: 0000
                  bit 1: error 1
                  bit 2: error 2
                  bit 3-32: error 3-32

**Comment by davidrapan** [comment]
```
- name: "Device Fault"
  class: "enum"
  rule: 3
  registers: [0x22B, 0x022C, 0x022D, 0x022E]
  icon: "mdi:message-alert-outline"
  lookup:
    - key: 0
      value: "OK"
    - bit: 6
      value: "DC/DC Soft Start failure"
    - bit: 9
      value: "Auxiliary power supply failure"
    - bit: 12
      value: "Working mode changed"
    - bit: 17
      value: "AC Over-current failure"
    - bit: 18
      value: "Tz_Integ_Fault failure"
    - bit: 19
      value: "DC Over-current failure"
    - bit: 22
      value: "AC current leakage failure"
    - bit: 63
      value: "Temperature is too high"
    - key: "default"
      value: "Error"
```

**Reply by murik85** [reply]
Thank you. I'll test it out

**Reply by murik85** [reply]
Tested it, it doesn't work. Perhaps errors from this and other registers are written to another register? On the inverter I can see them in one place one by one. There was one error during the test, but it was still “No Error”.

afore_hybrid.yaml

```
- name: "Alert DC"
        class: "enum"
        rule: 3
        registers: [0x0BC7]
        icon: "mdi:message-alert-outline"
        lookup:
          - key: 0
            value: "No Error"
          - bit: 16
            value: "E49_BusAllVoltSwUnderFault"
          - key: "default"
            value: "Error"
```
