### DISCUSSION TITLE
How do you use entities in the write multiple registers action?

### DISCUSSION THREAD

**Discussion by some0299** [davidrapan/ha-solarman#229] [Q&A] [answered]
After a bit of trial and error I've found that it is possible to set the time of use parameters on the ME3000 if you set them all using the Write Multiple Holding Registers (function code 16) Action. But I can't find a way to use the value of an entity in the values. Is there a way I could replace the 100 below with 'my_SOC_limit' entity?

action: solarman.write_multiple_holding_registers
data:
  register: 4615
  wait_for_attempts: 3
  values:
    - 0
    - 0
    - 5946
    - 100
    - 3000
    - 257
    - 3103
    - 127
    - 1
  device: 54bxxxxxx

**Comment by davidrapan** [comment, marked as answer]
```
action: solarman.write_multiple_holding_registers
data:
  device: 68cc2dc7f6d70d4742dca1d660cba099
  wait_for_attempts: 30
  register: 4615
  values:
  - 0
  - 0
  - 5946
  - '{{ states("input_number.my_SOC_limit") }}'
  - 3000
  - 257
  - 3103
  - 127
  - 1
```

Tip: Always set `wait_for_attempts: 30` to ensure 100% success.
