### DISCUSSION TITLE
How to read single register from multiple different modbus memory areas?

### DISCUSSION THREAD

**Discussion by murik85** [davidrapan/ha-solarman#242] [Q&A] [answered]
![0x04_0x03](https://github.com/user-attachments/assets/746cdeba-5cfa-496a-8d40-aef9711ec29a)

**Comment by davidrapan** [comment]
What do you mean?

**Reply by murik85** [reply]
Work:

  - group: Inverter
    code: 0x04
    items:
      - name: "Run State"
        rule: 1
        registers: [0x09C4]
        isstr: true
        lookup:
          - key: 1
            value: "Stand-by"
          - key: 2
            value: "Start"........


If I add ('EMSMode' "select"), 'Run State' stops working:

  - group: Inverter
    code: 0x04
    items:
      - name: "Run State"
        update_interval: 60
        rule: 1
        registers: [0x09C4]
        isstr: true
        lookup:
          - key: 1
            value: "Stand-by"
          - key: 2
            value: "Start"........

   - group: Settings
     code: 0x03
     items:
       - name: "EMS Mode"
         platform: select
         rule: 1
         registers: [0x09C4]
         lookup:
           - key: 0
             value: "SelfUse"
           - key: 1
             value: "ChrFst"............

**Reply by davidrapan** [reply]
Yes because they use the same register, you can only use one or the other. Just transform Run State into `platform: select`. You can still use it as sensor to show value. 😉 In other words, you don't really need two entities.

**Reply by murik85** [reply]
I did (RunState....select) - it doesn't fit, it doesn't update, and the EMSMode value (key1-key2.......) changes when selecting. The problem is that RunState should only be read (fc:0x04), and EMSMode should be changed (fc:0x06). And the register is the same. So we need two entities.

Maybe the update delay should be shifted: RunState (fc:0x04) update_interval: 15......EMSMode (fc:0x03) update_interval: 20. Though I doubt it will help.

I don't understand how it is organized in one register.

**Reply by davidrapan** [reply]
If you change that entity to select it does not affect how it's read, it will still use separate function codes for reading and writing...

So if you need 0x04 for reading and 0x06 for writing you add:
```
code:
  read: 0x03
  write: 0x06
```

You can find it for example [here](https://github.com/davidrapan/ha-solarman/commit/9989f567bce97b56f704a0bfa875991dc74e1758)

Edit: If your inverter uses single register like that it's not possible to create separate requests for single register using different modbus codes in current implementation.

Edit2: If I were you I would ditch the "Run State" and added only "EMS Mode" as select. 😉

Edit3: That update interval difference could maybe work but only if there are no overlaps over register 0x09C4.

**Comment by davidrapan** [comment]
Hey @murik85,

I evaluated your input as a valid feature request and thus implemented requesting to separate modbus memory areas in [feat: Add requesting to separate modbus memory areas](https://github.com/davidrapan/ha-solarman/commit/7bcb44af55dba698b5d61241d33e175bc9ac7aa9)

_Now you can define multiple entities with the same register addresses which are read using different modbus function codes._

**Test from your side would be appreciated.**

Thanks.

**Reply by davidrapan** [reply]
```
      - name: "Device State"
        rule: 1
        registers: [0x09C4]
        icon: "mdi:state-machine"
        lookup:
          - key: 0
            value: "Init"
          - key: 1
            value: "Standby"
          - key: 2
            value: "Startup"
          - key: 3
            value: "Grid"
          - key: 4
            value: "Grid disconnected"
          - key: 5
            value: "Generator"
          - key: 6
            value: "Off grid"
          - key: 7
            value: "On grid"
          - key: 8
            value: "Shutdown"
          - key: 9
            value: "Off"
          - key: 10
            value: "Error"
          - key: 11
            value: "Update"
          - key: 12
            value: "Aging"
          - key: 13
            value: "Open loop"
          - key: 14
            value: "Sampling calibration"

      - name: "Work Mode"
        update_interval: 300
        platform: select
        rule: 1
        code:
          read: 0x03
          write: 0x06
        registers: [0x09C4]
        lookup:
          - key: 0
            value: "Self Use"
          - key: 1
            value: "Charging First"
          - key: 2
            value: "Export First"
          - key: 3
            value: "Battery Maintenance"
          - key: 4
            value: "Command"
          - key: 5
            value: "EMS"
          - key: 6
            value: "Time of Use"
          - key: 7
            value: "Imbalance Compensation"
          - key: 8
            value: "Q Compensation"
```
