### DISCUSSION TITLE
Set/Clear Bit in register. (without touching any other bits)

### DISCUSSION THREAD

**Discussion by murik85** [davidrapan/ha-solarman#248] [Q&A] [answered]
Set/Clear Bit in register without touching any other bits?

![222](https://github.com/user-attachments/assets/53e852af-1294-4777-9426-50205af5ab60)

**Comment by davidrapan** [comment]
This would be another feature request. I see if I can do something about it. 😉

**Comment by davidrapan** [comment, marked as answer]
[feat: Switch platform - bitwise operations](https://github.com/davidrapan/ha-solarman/commit/7c163930fb7e29c8940c6a41d933f5049e7ce454):
```
      - name: Clear records
        platform: switch
        rule: 1
        registers: [0x0210, 0x020F]
        value:
          bit: 5
```

Edit: OR if the register has "auto-reset capability" or/and you want to use simple button ...

[feat: Button platform - bitwise operations](https://github.com/davidrapan/ha-solarman/commit/ccb44797a46cc3e79fe43fca24cf3b4eb57188f2):
```
      - name: Clear records
        platform: button
        rule: 1
        registers: [0x0210, 0x020F]
        value:
          bit: 5
```

Edit2: [feat: Add support for writing of values > 16b](https://github.com/davidrapan/ha-solarman/commit/5800608641833cd8d4c979f135deece5fa1ac3aa) will be proly needed too.

Edit3: [refactor: Moved bit prop in Button & Switch platforms](https://github.com/davidrapan/ha-solarman/commit/3ce2148eeabb19c0c7b285cae9e0e8d6b7e63086) is needed too.

Edit4: [fix: Button & Switch platforms typo](https://github.com/davidrapan/ha-solarman/commit/ae6b1d1f4935f0852313439e9cf3062536c2b329)

Edit5: [fix: Bidirectional writing across multiple registers](https://github.com/davidrapan/ha-solarman/commit/72020f3264619ad5566df0b251b536668f65ef1e)

Edit6: [fix: SolarmanWritableEntity - TypeError: 'int' object is not iterable](https://github.com/davidrapan/ha-solarman/commit/83a358044bb57afd7628194bd10d2e66dc27ad35)

Edit7: [refactor: Writing of 32b registers](https://github.com/davidrapan/ha-solarman/commit/9d4a793e8d62ac9799be47b7ba43d6a24940c238)
