### DISCUSSION TITLE
Testing with Solis Inverter

### DISCUSSION THREAD

**Discussion by gedger** [davidrapan/ha-solarman#26] [General]
If you would prefer any of these raised as issues then please let me know.

I realise the integration is undergoing a lot of changes at the moment but I think there needs to be some regular (daily?) beta releases. I've installed via HACS and hence have version 24.07.14 and there are several items not working 100%, for example the update_interval doesn't work? I suspect these items have already been fixed but as there are no other later releases it's hard to raise an issue against a specific version. Hence I haven't raised any issues yet....

I found it odd to have to specify battery parameters on the configuration page when my inverter has no battery. Wouldn't these items be better in the configuration file for each inverter?

Several of my template sensors failed as they were being triggered by a last_update_sensor provided by the StephenJoubert integration but not yours. As many people will be moving from that integration it may be useful to add a migration help page which we can add these type of observations to? 

On the big plus side the integration is a huge improvement over the StephenJoubert variant so a huge thanks for taking this on.

**Comment by davidrapan** [comment]
Hi! Thanks for your post!

I set the release cycle for 04., 14. and 24. every month and also the versioning will match those so it's clear. When comes to dev versions I try to always keep the current main in a "working" state but there is no guarantee sure. I was thinking maybe some nightly dev cycle but I still did not put much thought into it yet!

Currently if you are on the 24.07.14 and did not download code manually you can refer that version with no problems.

When comes to the configuration yes the Battery Settings and some others are still a subject to change and I will use OptionsFlow for it in the future.

Last Updated value is part of the Connection sensor and you can read it like this:
```
states.sensor.inverter_connection_state.last_updated | as_local
```
I have planned in near future to also extend this diagnostic part from the integration rather than using 'configuration.yaml' separatedly. But I'm still learning about the HA so it's a journey, haha. 😉

Could you maybe show how did you used the sensor? So I can better help you with the migration? But I'm sure that with Stephan's integration there was really need for that because of the stability issues and it really should not be a problem here. You should always have the most recent and correct values and if that's not the case there is something wrong and should be fixed rather than patched with some detection mechanics.

**Reply by gedger** [reply]
My inverter doesn't provide the power per string so I calculate it from the Volts and Current using a template sensor. The issue I had was that HA updates the template sensor every time one of the used sensors changes state. In Stephans integration there was a delay between the Volts and Current sensors being updated so HA calculated New Volts * Old Amps, then New Volts * New Amps. This gave some nasty glitches in the output. I solved it by using a trigger to only do the calculation once everything had been updated and the last updated sensor was always updated after ALL the values had been updated. Here's an example.

```
- trigger:
  - platform: state
    entity_id:
      - sensor.solis_status_lastupdate
  sensor:
  - name: PV1 DC Power
    unit_of_measurement: kW
    device_class: power
    state_class: measurement
    state: >-
      {% set v = states('sensor.solis_pv1_voltage') %}
      {% set a = states('sensor.solis_pv1_current') %}
      {% if is_number(v) and is_number(a) %}
      {{ (v|float * (a|float+0.1) / 1000.0) | round(3) }}
      {% else %}
        0
      {% endif %}
```

**Reply by davidrapan** [reply]
What inverter profile are you using? Does this out of sync update of volts and amps also happens in my integration? If I remember correctly Stephans integration relied on set requests and that means that some values were not from the same batch. That should not be the case in my implementation. But that does not mean that inverter still has some caveats which still does this (in my opinion) nonsense. But we will fix it! :)

Just tell me the profile and I show you how to do it without manual configuration in 'configuration.yaml'

But you will have to wait with that until next release. Where will be present all the necessary changes!

😉

**Reply by gedger** [reply]
I'm using the solis_1p8k-5g.yaml configuration which I created and pushed into Stephans integration so I could well be the only person using it 😄

**Reply by davidrapan** [reply]
I see there is a PV Power both only as a Total? And you also want each separatedly? You sure there are no registers for it, right?

"float+0.1" does this what i think it does? 😆

**Reply by davidrapan** [reply]
This could be placed in your profile:
```
- name: PV1 Power
  class: "power"
  state_class: "measurement"
  uom: "kW"
  rule: 1
  digits: 3
  registers: [3021, 3022]
  sensors:
    - registers: [3021]
      scale: 0.1
    - operator: multiply
      scale: 0.001
      registers: [3022]
```

But after today's commit, I still had to add multiply and divide operators.

_But still don't know about that +0.1._ 😆

**Reply by gedger** [reply]
Excellent, thank you.  The 0.1 was a fiddle factor to try and calibrate the result but it can be removed. There was no register I could find that gave the individual string power output....

I also calculate inverter efficiency. The ([0, eff, 99]|sort)[1] was to ensure the value was always between 0-99 as I did get the occasional bonkers value....

```
- trigger:
  - platform: state
    entity_id:
      - sensor.solis_status_lastupdate
  sensor:
  - name: Solis Inverter Efficiency
    unit_of_measurement: '%'
    state_class: measurement
    state: >-
      {% set ac_power = states('sensor.solis_inverter_ac_power')|float(0) %}
      {% set dc_power = states('sensor.solis_total_dc_power')|float(0) %}
      {% if ac_power and dc_power %}
      {% set eff = (ac_power / dc_power * 100)|round(1) %}
      {{ ([0, eff, 99]|sort)[1] }}
      {% else %}
        0
      {% endif %}
```

**Reply by davidrapan** [reply]
```
- name: Inverter Efficiency
  class: ""
  state_class: measurement
  uom: "%"
  rule: 1
  digits: 1
  uint: enforce
  registers: [3005, 3004, 3007, 3006]
  sensors:
    - signed:
      registers: [3005, 3004]
    - operator: divide
      signed:
      scale: 100
      registers: [3007, 3006]
  validation:
    min: 0
    max: 99
```

**Comment by gedger** [comment]
For some reason I can't get the inverter efficiency working....but the PV power works fine. I'll keep investigating...

Some other sensors that used the scale_division option have also stopped working, will these need converting to use the new operator  syntax?

```
    - name: "WStatus Derating"
      class: ""
      state_class: ""
      uom: ""
      scale_division: 32
      rule: 1
      mask: 0x20
      registers: [3071]
      icon: 'mdi:list-status'
```

**Reply by davidrapan** [reply]
'scale_division' was something i noticed as latest features of Stephans integration. But that was after I was working on mine. What's it supposed to do anyway?

And what do you mean by not working? What it shows?

First thing what comes to my mind try to double check if there is correct order of low 16 bits and high 16 bits.

**Reply by gedger** [reply]
It divides the answer by a value, in my case 32 and is useful for bit fields. In the example it first masks the bitfield to select bit 6 (mask: 0x20) then shifts right (scale_div: 32) to create an 1 or 0 if bit 6 is active.

**Reply by davidrapan** [reply]
Ah sure, makes sense. I didn't need it yet so... But I can add it. ;)

**Reply by davidrapan** [reply]
[a677eb3](https://github.com/davidrapan/ha-solarman/commit/a677eb3866b3de7223059efc4d53bab7336df177)

I put it there so let me know when you'll have the chance to test it as I'm unsure if i picked the correct pos where to do the operations. 😉

**Reply by davidrapan** [reply]
I found an use-case for it so I tried it and it looks like it works! [f359b59](https://github.com/davidrapan/ha-solarman/commit/f359b59eef62b752d7f6bacdaf1640af7825faa5)

**Comment by gedger** [comment]
Solved the inverter efficiency, by changing where the scaling is done? So

```
      sensors:
        - registers: [3005, 3004]
          signed:
        - operator: divide
          signed:
          scale: 100
          registers: [3007, 3006]
```
becomes

```
      sensors:
        - registers: [3005, 3004]
          signed:
          scale: 100
       - operator: divide
          signed:
          registers: [3007, 3006]
```
and it all works?
