### DISCUSSION TITLE
General understanding of grid charging automation

### DISCUSSION THREAD

**Discussion by albertusQuelle** [davidrapan/ha-solarman#270] [General]
hi David, 
i read your YAML snippet [here](https://github.com/davidrapan/ha-solarman/discussions/225#discussioncomment-10983208)

Is that an update to this Grid Charging automation? https://github.com/davidrapan/ha-solarman/wiki/Automations

I have a basic understanding question. 
You  mention Charge battery during T2. Does T2 mean during time of use 2?

Because nowhere in the code you refer to the TimeofUse. 
I am using deye 12K-SG04LP3-EU

**Comment by davidrapan** [comment]
> Is that an update to this Grid Charging automation?

Yes.

> You mention Charge battery during T2. Does T2 mean during time of use 2?

It's energy tariff. T2 is off peak and T1 is peak.

**Reply by albertusQuelle** [reply]
Thank you. 
This means T = Tariff. 
Its tariff 1 and tariff 2. 

Do i have to set peak and off peak by myself? 
I assume you mean with peak (highest price) and off peak lowest price?

**Reply by davidrapan** [reply]
> Do i have to set peak and off peak by myself?
I assume you mean with peak (highest price) and off peak lowest price?

Yes. You have to setup the automation according to your off peak hours. In my case they are (and how it's setup in the example) 3 AM - 6 AM.

**Reply by albertusQuelle** [reply]
Ah understood. 
Means the time where we expect that the price of the current is low at that time. 

Do we have to merge your code from [here](https://github.com/davidrapan/ha-solarman/discussions/225#discussioncomment-10983208) and [here](https://github.com/davidrapan/ha-solarman/wiki/Automations#inverter-grid-charging-program)?

**Reply by davidrapan** [reply]
Just the first one, and create template sensor which will control max SOC for the automation.

**Reply by albertusQuelle** [reply]
Means you dont use this code anymore: 

```
alias: Inverter Grid Charging Program
description: Charge battery during low price on bad solar forecast
triggers:
  - at: sensor.sun_next_dawn
    trigger: time
  - value_template: >-
      {% if states('sensor.solcast_pv_forecast_forecast_today') | float > 0
      %}true{% endif %}
    trigger: template
conditions:
  - condition: time
    after: "03:00:00"
    before: "06:00:00"
  - condition: state
    entity_id: input_select.grid_metrics_tariff
    state: T2
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            above: 50
```


You use this code at the beginning of your automation?


```
alias: Inverter Grid Charging Program
mode: single
triggers:
  - at: "03:00:10"
    trigger: time
  - at: "04:00:00"
    trigger: time
  - at: "05:00:00"
    trigger: time
actions:
  - sequence:
      - action: solcast.update_forecasts
        data: {}
      - action: number.set_value
        metadata: {}
        target:
          entity_id: number.inverter_program_1_soc
        data:
          value: "{{ states('sensor.inverter_battery_precharge') }}"
```
