### DISCUSSION TITLE
How can we read (multiple) bits from registers

### DISCUSSION THREAD

**Discussion by PitinoB** [davidrapan/ha-solarman#314] [Q&A]
![image](https://github.com/user-attachments/assets/185e5382-4978-4acd-add6-3981116a1113)

I need help with writing yaml code.
How can I read bits from registers?
Register 0x3104 return integer like 12610 or 12866.
I need to get values in table for that number.

Thanx

**Comment by davidrapan** [comment]
You can select specific bit with:
```
bit: {index}
```
added into entity description.

**Comment by PitinoB** [comment]
I dont know how to read bits from 0 to 4 and then get integer from 0 - 17 like in a table.
I tray with 
lookup:
  - bit; [0,1,2,3,4]

but not working

**Comment by davidrapan** [comment]
Show me full entity description and please don't forge to wrap the yaml snippet in \`\`\`{code}\`\`\` (It's simple, just select text which belongs to the yaml snippet and click on button which looks like this "<>").

**Comment by PitinoB** [comment]
```
- group: Alarm-State
  items:
    - name: "DSP State"
      update_interval: 5
      class: "enum"
      rule: 1 # unsigned 16
      registers: [0x3104]
      bit: 2
```

**Comment by PitinoB** [comment]
this reads single register and return value 0 or 1
but I want to read five registaers at once

**Comment by davidrapan** [comment]
Ah sure, I get it now! 😉 You need to use mask:
```
mask: 0x1F
```

**Comment by davidrapan** [comment]
And there is also another route you can take:
```
      - name: "Device Alarm"
        class: "enum"
        rule: 3
        registers: [0x0229, 0x022A]
        icon: "mdi:alert-outline"
        lookup:
          - key: 0
            value: "OK"
          - bit: [0, 1, 2, 3, 4]
            value: "{state_description}"
          - key: "default"
            value: "Error"
```

**Comment by PitinoB** [comment]
Thank You for your help and tips.
The example below works.
```
      - name: "DSP State DCDC"
        class: "enum"
        rule: 1 # unsigned 16
        registers: [0x3104]
        mask:
          0x0700 # bit   10  ,  9  ,  8
          #             1024 , 512 , 256
          #               4  ,  2  ,  1
        lookup:
          - key: 0 # 000 -> 0 -> 0
            value: "Standby"
          - key: 256 # 001 -> 1 -> 256
            value: "Charging"
          - key: 512 # 010 -> 2 -> 512
            value: "Discharging"
          - key: 768 # 011 -> 3 -> 768
            value: "Service"
          - key: 1024 # 100 -> 4 -> 1024
            value: "Test"
```

**Reply by GuavaFortress** [reply]
Hi @PitinoB 
Would you be able to guide me on how you concluded on 0x0700 as the mask value, as well as the value for each key? I am trying to do the same for Sysstatus, INVstatus, Alarm, and Fault codes. Or if you can share the codes that you may already have for those that would be cool too. Thank you.

**Reply by PitinoB** [reply]
Register 3104 is divided into three parts, namely the first part bit 0 to bit 4, the second part bit 5 to bit 7 and the third part bit 8 to bit 10. In decimal, the first part is 1+2+4+8+16=31 and the mask is 31 hexadecimal 0x1F, the second part = 32+64+128=224 and the mask is 224 hexadecimal 0xE0 and the third part 256+512+1024=1792 and the mask is 1792 hex 0x0700. In 3 bits (8-10) we can write a maximum of 8 numbers from 0 to 7. 0=0(0), 1=256(1), 2=512(2), 3=256+512(1+2), 4=1024(4)........7=256+512+1024(1+2+4)

What is on which number, the inverter manufacturer must tell you.

**Reply by GuavaFortress** [reply]
Hi @PitinoB 

Thank you! I think that now I understand how to calculate the mask and the keys. I have three questions:

1. Online calculators are showing me that the hexadecimal of 1792 is (700)16, why would you use 0x0700 instead of 0x700 for the mask?
 
2. I can see that we can write a maximum of 8 numbers from 0 to 7. Zero is Zero. I am assuming that One is 256 because that’s the value of the eight bit from previously?

3. What does it mean that it is necessary to read 5 registers consecutively and how? Or should I ignore this?

<img width="620" height="246" alt="image" src="https://github.com/user-attachments/assets/c6f1a4b3-89c9-4bdd-bc33-752d6f976a79" />

**Reply by PitinoB** [reply]
1. I always write hex in pairs, you can leave out the leading 0
2. 8 numbers can be written in 3 bits (0 + 1-7), 32 numbers can be written in 5 bits (0 + 31). Yes.
3. I read the first 5 bits like this and it works for me

```
      - name: "DSP State System"
        class: "enum"
        rule: 1 # unsigned 16
        registers: [0x3104]
        mask: 0x1F
        lookup:
          - key: 0
            value: "Init"
          - key: 1
            value: "Standby"
          - key: 2
            value: "PV Grid"
          - key: 3
            value: "BAT Grid"
          - key: 4
            value: "Hybrid Power"
          - key: 5
            value: "AC BAT Charging"
          - key: 6
            value: "PV BAT Charging"
          - key: 7
            value: "Bypass"
          - key: 8
            value: "Fault"
          - key: 9
            value: "Self Check"
          - key: 10
            value: "DSP FU"
          - key: 11
            value: "ARM FU"
          - key: 12
            value: "Service"
          - key: 13
            value: "Inverter Test"
          - key: 14
            value: "PV Test"
          - key: 15
            value: "DCDC Test"
          - key: 16
            value: "Test Mode"
```

**Reply by PitinoB** [reply]
I can't give you my registers because I have a different inverter. Sorry.

**Reply by PitinoB** [reply]
I don't know what they mean by reading 5 registers.
If it says next to the register that it needs 4 bytes then you have to read two registers. See under data.
You read the one written and the next one. For example, register 0x3153 has 4 bytes, so you also have to read register 0x3154.

**Reply by GuavaFortress** [reply]
Okay, that's good to know about the 4 bytes. With your help I was able to get the device, inverter, and DC-DC sensors running. Now I am turning my attention to Alarm 1 on 0x3100. The problem that I am having is that when I have two alarms at the same time, for example bit 2 (Bat Disconnected) and bit 4 (Bat Low Capacity), instead of reading them separately as 2 and 4, it is reading it as 24. If this is something that you have experienced and are able to share a solution I would appreciate it.

**Reply by PitinoB** [reply]
I haven't read these registers. But I think they should be read like this.

```
      - name: "Device Alarm"
        class: "enum"
        rule: 3
        registers: [0x3100, 0x3101]
        icon: "mdi:alert-outline"
        lookup:
          - key: 0
            value: "OK"
          - bit: 0
            value: "Discharge over current"
          - bit: 1
            value: "Over Load"
          - bit: 2
            value: "Bat Disconnect"
          - bit: 3
            value: "Bat Under Volt"
          - bit: 4
            value: "Bat Low Capacity"
          - bit: 5
            value: "Bat Over Volt"
          - bit: 6
            value: "Grid Low Volt"
          - bit: 7
            value: "Grid Over Volt"
          - bit: 8
            value: "Grid Low Freq"
          - bit: 9
            value: "Grod Over Freq"
          - bit: 10
            value: "Gfci Over"
          - bit: 11
            value: "Parallel CAN Fail"
          - bit: 12
            value: "Grid CT Reverse"
          - bit: 13
            value: "BUS Under Volt"
          - bit: 14
            value: "BUS Over Volt"
          - bit: 15
            value: "INV Over Current"
          - bit: 16
            value: "Charge Over Current"
          - bit: 17
            value: "BUS Volt OSC"
          - bit: 18
            value: "INV Under Volt"
          - bit: 19
            value: "INV Over Volt"
          - bit: 20
            value: "INV Freq Abnor"
          - bit: 21
            value: "IGBT Temp High"
          - bit: 22
            value: "BMS sys erro"
          - bit: 23
            value: "Bat Over Temp"
          - bit: 24
            value: "Bat Under Temp"
          - bit: 25
            value: "Bat Cell Unball"
          - bit: 26
            value: "Bat Reverse"
          - bit: 27
            value: "BMS Comm Fail"
          - bit: 28
            value: "Fan Fail"
          - bit: 29
            value: "Grid Over Load"
          - bit: 30
            value: "Grid Phase ERR"
          - bit: 31
            value: "ARC Fault"
          - key: "default"
            value: "Error"
```
I put this in my definition.yaml but I can't test if it works. If you can test it, please let me know if it works.

**Reply by GuavaFortress** [reply]
@PitinoB 

I did some testing, and this is what I found:

1. Registers 0x3100 (Alarm 1) and 0x3101 (Alarm 2) are two different entities and must be separate. Otherwise, they will use the same lookup bits. In your example above, if Alarm 2 is triggered by bit 2, it will show "Bat Disconnect", which is incorrect. I suppose that the two registers could be combined only if lookup keys are used instead of bits (more on this later). Bits higher than 16 do not exist on the table.

2.   Once the two registers are separated, they will work as intended as long as there is only one single error at a time per register. If there are two error codes or more, it will simply display value "Error" from the default key, and the errors will not be listed. 

3. I was able to list multiple errors by using their key. For example, the combination of bits 3,4,5 have a key of 0x38. This does mean that every possible error combination would have to be known. But I am only going to put down those combinations that are common such as "Bat Low Cap" and "Bat Low V". In order to read the key of a bit combination, change the rule value of the register to 6 while the errors are active. Then simply check the sensor value, enter the new key entry to the inverter definition file, and change the rule back to 3 when done.  

The Alarm 1 entry would look something like this:

```
      - name: "Device Alarm 1"
        class: "enum"
        rule: 3
        registers: [0x3100]
        icon: "mdi:alert-outline"
        lookup:
          - key: 0
            value: "OK"
          - bit: 0
            value: "Discharge over current"
          - bit: 1
            value: "Over Load"
          - bit: 2
            value: "Bat Disconnect"
          - bit: 3
            value: "Bat Under Volt"
          - bit: 4
            value: "Bat Low Capacity"
          - bit: 5
            value: "Bat Over Volt"
          - bit: 6
            value: "Grid Low Volt"
          - bit: 7
            value: "Grid Over Volt"
          - bit: 8
            value: "Grid Low Freq"
          - bit: 9
            value: "Grod Over Freq"
          - bit: 10
            value: "Gfci Over"
          - bit: 11
            value: "Parallel CAN Fail"
          - bit: 12
            value: "Grid CT Reverse"
          - bit: 13
            value: "BUS Under Volt"
          - bit: 14
            value: "BUS Over Volt"
          - bit: 15
            value: "INV Over Current"
          - key: 0x38 # Errors charging frozen bat and charge power is insufficient to run bat internal heaters
            value: "Bat Under Capacity, Bat Low Capacity, Bat Over Volt"
          - key: "default"
            value: "Error"
```

If you or someone else knows of a better way to display multiple error codes when they happen within a register, I would be happy to know how. I already tried "bit_lookup_multiple" but it did not work.
