### DISCUSSION TITLE
Issues with House Load Display HYD 20 KTL-3PH (LSE-3)

### DISCUSSION THREAD

**Discussion by lowcloud** [davidrapan/ha-solarman#332] [Q&A]
Hello everyone,

I’m new to this and currently working with a Sofasolar HYD 20 KTL-3PH (SN: P1, definition: sofar_g3hyd.yaml) and the LSE-3 Logger (FW 1.09). The ha-solarman integration is running stable so far. Now, I’d like to start with a few simple analog display cards, such as one for the current house load in watts.
I suspect that I need to calculate the house load using the following values, as they seem to be the only meaningful and available power metrics:

- Inverter Active Power Load Sys
- Inverter Active Power PCC Total
- Inverter Active Power Output Total

e.g.:

![image](https://github.com/user-attachments/assets/6e55fef6-eefe-4080-b3fc-82dbac29fc9a)

The values Inverter Reactive Power PCC Total and Inverter Reactive Power Load Total EPS etc. always show 0 W.

e.g.:

![image](https://github.com/user-attachments/assets/84eef037-d456-4159-bee3-a14134e2b22e)

I’ve created a Template Sensor but I’m not sure if the calculation is correct. The Solarman app reports a different higher value for the current consumption. Here's my current sensor configuration:
```
template:
- sensor:
      - name: "house load"
        unit_of_measurement: "W"
        state: "{{ states('sensor.inverter_active_power_output_total') | float - states('sensor.inverter_active_power_pcc_total') | float }}"
```
Does anyone have an idea why there’s a discrepancy between the values, or any tips for calculating and displaying the house load?

Thank you in advance for your help!
