### DISCUSSION TITLE
Need sensors Battery Power

### DISCUSSION THREAD

**Discussion by vind11** [davidrapan/ha-solarman#372] [Q&A] [answered]
There is no "Battery Power" register in the inverter SRNE. I am trying to get it by next way:
 - name: "Battery Power"
        class: "power"
        state_class: "measurement"
        uom: "W"
        rule: 2
        digits: 3
        scale: 0.1
        registers: [0x0101, 0x0102]
        sensors:
          - registers: [0x0101]
            multiply:
              registers: [0x0102]
        icon: "mdi:solar-power-variant"

. but since 1 of the parameters can be negative - the result does not work. Is there any way to solve this?

**Comment by davidrapan** [comment]
Hi @vind11, what do you mean by doesn't work? Be more specific please.

**Reply by vind11** [reply]
![123](https://github.com/user-attachments/assets/23e7fa6e-217e-468c-b8b9-c89c6a0b47c3)
as "Battery Voltage" 16-bit unsigned integer ranging from 0 to 65,535,, and "Battery Current" 16-bit signed integer ranging from -32,767 to 32,767 multiply has bad result then "Battery Current" has negative value , see picture
then "Battery Current" has positive value -  "Battery Power" is ok

**Reply by vind11** [reply]
I try next:
name: "Battery Power"
        class: "power"
        state_class: "measurement"
        uom: "W"
        rule: 2
        digits: 3
        scale: 0.1
        registers: [0x0101, 0x0102]
        sensors:
          - registers: [0x0101]
            multiply:
              registers: [0x0102]
              rule: 2

also not woring

**Reply by davidrapan** [reply]
Which register is voltage and which is current?

**Reply by vind11** [reply]
101 voltage
102 current

**Reply by davidrapan** [reply]
Try to set `rule: 1`

_Make sure you did not add any properties twice as you did in your previous code example._ 😉

**Reply by vind11** [reply]
> Try to set `rule: 1`

not working !

**Reply by goldserve** [reply]
Any update on this? I'm trying to calculate values as well so I could learn a thing or two.

**Comment by vind11** [comment]
Unfortunately, there is none yet. You can make a template, but I would like a more elegant solution. I'm just not a programmer.

**Comment by davidrapan** [comment, marked as answer]
```
      - name: Battery Power
        class: "power"
        state_class: "measurement"
        uom: "W"
        rule: 1
        scale: 0.1
        digits: 2
        registers: [0x0101, 0x0102]
        sensors:
          - registers: [0x0101]
          - operator: multiply
            signed:
            registers: [0x0102]
```
