### DISCUSSION TITLE
Set modbus register 22, 23 and 24 with current date and time while starting to prevent Yield today break

### DISCUSSION THREAD

**Discussion by RothMick** [davidrapan/ha-solarman#383] [Q&A] [answered]
First of all, thank you for your great HA implementation. I use it for my two Deye Sun800 microinverters and it works pretty perfectly.
I have had some bad experiences with forced firmware updates controlled from China. I want to avoid that and so I disabled the internet connection for the Deyes via my router. Unfortunately, the data for today's yield (at the Deyes) is not reset because the date and time are not updated without internet access to the Solarman or Deye cloud.
**Idea: Could your implementation be extended, so that it sets the date in the modbus registers 22, 23 and 24 as soon as the inverter wakes up and connects?**

**Comment by davidrapan** [comment, marked as answer]
Hi @RothMick, thank you for your kind words! You can already set time using HA automation which can have trigger when device comes back online:
```
alias: Inverter Time Synchronization
description: Set device's time to `now()`
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.inverter_connection
    to: "on"
conditions: []
actions:
  - data:
      datetime: "{{ now() }}"
    target:
      entity_id: datetime.inverter_date_time
    action: datetime.set_value
mode: single
```

Also there is a better way of cutting off connection to solarman servers. By clearing out **Server A & Optional Server Setting** input boxes at http://{inverter_ip}/config_hide.html
