### DISCUSSION TITLE
AntiReflux_Power modify parameter - control grid sales

### DISCUSSION THREAD

**Discussion by pustek** [davidrapan/ha-solarman#408] [Ideas]
Hi, I would like to ask, how dificult is to add change of parameter AntiReflux_Power, it is number in Wats. Like how much you want to send back to provider. If I am on SPOT I need to turn to 0 when price is minus value. I have spot price sensor already.

I found it in Sofar Modbus doc as: 0x1000 -0x10FF

Basic configuration(0x1000-0x10FF)
1024 | AntiReflux_Power | U16 | 100 | W | 0 | 65535 | RW | Anti-backflow power | Installers

There is "Installers" sign and I have only user account for integration.
To enter Installer mode I have to use Application and Bluetooth - Local Control.

Do anybody know if is possible by this integration or I need ESP32 with bluetooth to control it?
SOFAR Solar, HYD 10KTL-3PH

Thanks!
Tomas

**Comment by pustek** [comment]
I probably found some topic related https://github.com/wills106/homeassistant-solax-modbus/issues/421

**Reply by davidrapan** [reply]
Sure, I think I can try adding them. What profile are we talking about here?

**Reply by pustek** [reply]
Hi, I found that topic about modbus not for my case I have wifi loger LSW3 which is not working there.

Are you able to add those controls for AntiReflux_Power? The profile is sofar_g3hyd.yaml :)

**Reply by davidrapan** [reply]
Sure I can, this integration also uses modbus under the hood. 😉

**Reply by pustek** [reply]
I just add to my sofar_g3hyd.yaml

      - name: "AntiReflux_Power"
        state_class: "measurement"
        uom: "W"
        rule: 1
        registers: [0x1024]
        icon: "mdi:battery-low"


It shows 98W there is 9800W set in real. So it just need *100 :) then it is fixed.

Now the trick will be how to change/control...

**Reply by davidrapan** [reply]
```
      - name: Export Surplus Limitation
        platform: select
        rule: 1
        registers: [0x1023]
        lookup:
          - key: 0x0000
            value: "Disabled"
          - key: 0x0001
            value: "Enabled"
          - key: 0x0002
            value: "Balanced"

      - name: Export Surplus Power
        platform: number
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 100
        rule: 1
        registers: [0x1024]
        range:
          min: 0
          max: 65535
```

**Reply by davidrapan** [reply]
[feat: Add Export Surplus Limitation configuration for Sofar G3](https://github.com/davidrapan/ha-solarman/commit/c6fdd4fb9d328a7efc2f31747ebbae0e8466ba3b)

**Reply by pustek** [reply]
Hi, good! value is there, but I get this when change to 0: Failed to perform the action number/set_value. Incorrect response w/ function code 144 instead of 16 received

**Reply by davidrapan** [reply]
Enable debug logging, try to change the value and then attach the file here please.

Edit: It looks like it requires write of both registers at the same time you can try following:
* Open Developer tools > ACTIONS > Solarman: Write Multiple Registers (Modbus Function Code 16)
* Select your device
* Click GO TO YAML MODE
* Change the input like this:
```
action: solarman.write_multiple_registers
data:
  device: {Your device}
  address: 4131
  values:
    - 0
    - 90
```

_Value 0 is disabled limitation mode and 90 is power which will be set as multiply of 100._

**Reply by pustek** [reply]
yes, it seems so, after run this debug, value changed to 9000W :)




2025-02-14 11:43:41.204 DEBUG (MainThread) [custom_components.solarman.device] [2759811366] Querying 03 ❘ 0x03 ~ 4132 - 4132 ❘ 0x1024 - 0x1024 #001 succeeded
2025-02-14 11:43:41.204 DEBUG (MainThread) [custom_components.solarman.device] [2759811366] Querying 03 ❘ 0x03 ~ 4173 - 4178 ❘ 0x104D - 0x1052 #006 ...



[home-assistant_solarman_2025-02-14T10-45-08.769Z.log](https://github.com/user-attachments/files/18797959/home-assistant_solarman_2025-02-14T10-45-08.769Z.log)

**Reply by pustek** [reply]
It works like this, without issue:

action: solarman.write_multiple_registers
data:
  address: 4131
  device: {Your device}
  values:
    - 98
    - 98

action: solarman.write_multiple_registers
data:
  address: 4131
  device: {Your device}
  values:
    - 0
    - 0

**Reply by davidrapan** [reply]
The first value is mode:
* 0: Disabled
* 1: Enabled
* 2: Balanced

Second value is power and is multiplied by 100.

**Reply by pustek** [reply]
I will change just 0x1024 value because 0 means no owerflow and they says is the best to do like this. No need to change first value 0x1023. 

Anyway it seems started working without problem with use any combination of this action:

action: solarman.write_multiple_registers
data:
  address: 4131
  device: {Your device}
  values:
    - 0-2
    - 0-100



1
0

1
98

**Reply by davidrapan** [reply]
No, this ACTION just exposes direct write of modbus registers.

On top of that second register/value (0x1024) **has range 0-65535 which means that your 100% would equal to 6553500 W**.

**Reply by pustek** [reply]
yes, you right, I just edit my previous comment :)

**Reply by davidrapan** [reply]
I can help you create select and number templates w/ automation in HA to control both register using HA entities if you want as It's currently not possible to control more then one register at a time using the integration.

**Reply by pustek** [reply]
I need just set 0 or 98 only for my 10kw. I dont know if for others who have 6kw want set 0 and 58?

I also found anbother vallue "Battery EPS Buffer" will be nice to control. It is like after solar season, if you need more buffer in battery :)

**Reply by pustek** [reply]
Hi, is anything I should do? :) I would like but still somehow strugling with understanding of it.
Will be possible to use those templates in my Automation @ scenes somehow?

**Reply by pustek** [reply]
- id: '1739635880144'
  alias: SPOT under 0kc - test
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.current_market_price_czk_kwh
    below: 3
  conditions: []
  actions:
  - action: solarman.write_multiple_registers
    data:
      address: 4131
      device: deviceID
      values:
      - 1
      - 0

**Reply by pustek** [reply]
this seems working

**Comment by pustek** [comment]
```
- id: 'XXX'
  alias: SPOT 0kc POD - VYPINANI PRETOKU
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.current_market_price_czk_kwh
    below: 0
  conditions:
  - condition: numeric_state
    entity_id: sensor.inverter_antireflux_power
    above: 0
  actions:
  - action: solarman.write_multiple_registers
    data:
      address: 4131
      device: <your device id>
      values:
      - 1
      - 0
  mode: single


- id: 'XXXX'
  alias: SPOT 0kc NAD -  ZAPINANI PRETOKU
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.current_market_price_czk_kwh
    above: 0
  conditions:
  - condition: numeric_state
    entity_id: sensor.inverter_antireflux_power
    below: 1
  actions:
  - action: solarman.write_multiple_registers
    data:
      address: 4131
      device: <your device id>
      values:
      - 1
      - 98
  mode: single
```
