### DISCUSSION TITLE
HA Solarman Write Register to allow for formula in the value

### DISCUSSION THREAD

**Discussion by goldserve** [davidrapan/ha-solarman#472] [Q&A] [answered]
Previously I was using HA modbus to write this register but since I got solarman working with my inverter, I tried to switch over to using solarman action as follows:

```
action: solarman.write_single_register
metadata: {}
data:
  device: 7d2592cdcbb1797a9ecaa77189fcd712
  register: 8452
  value:
    - >-
      {{ "%04x" | format( (now().timestamp()| timestamp_custom("%H")) | int *
      256) | int(base=16,default=0)}}
    - >-
      {{ "%02x" | format( (now().timestamp()| timestamp_custom("%H")) | int + 1)
      | int(base=16,default=0) * 256}}
```

However, this fails because the value is not an expected dictionary value.
![Snip20250313_6](https://github.com/user-attachments/assets/d0406eda-c737-4f4d-ba35-3b551cd4d47a)

**Comment by davidrapan** [comment]
Hi @goldserve, because you are using single register write w/ multiple values in value parameter. You need to use Write Multiple Registers..

**Comment by goldserve** [comment]
I changed it so that it writes one 16-bit int but it's still not working.

```
Executed: March 14, 2025 at 9:22:28 AM
Error: expected int for dictionary value @ data['value']
Result:
params:
  domain: solarman
  service: write_single_register
  service_data:
    device: 7d2592cdcbb1797a9ecaa77189fcd712
    register: 8452
    value:
      - 2304
  target: {}
running_script: false
```

**Reply by davidrapan** [reply]
But you are still using list notation. Change it to `value: ???`

**Comment by goldserve** [comment, marked as answer]
Ah yes, It is fixed now. It should read:

```
action: solarman.write_single_register
metadata: {}
data:
  device: 7d2592cdcbb1797a9ecaa77189fcd712
  register: 8452
  value: >-
    {{ "%04x" | format( (now().timestamp()| timestamp_custom("%H")) | int * 256)
    | int(base=16,default=0)}}
enabled: true
```
