### DISCUSSION TITLE
How to upload data to PVOutput.org

### DISCUSSION THREAD

**Discussion by PV-Joe** [davidrapan/ha-solarman#479] [Q&A] [answered]
This is just an idea.

Would it be possible to add the ability to upload data from Solarman for Home Assistant to:
[https://pvoutput.org]()?

PVoutput is a free service to share and compare PV output data.

**Comment by davidrapan** [comment]
Hi @PV-Joe, great idea indeed! There is already [a thread about this](https://community.home-assistant.io/t/pvouput-uploader/46761) with the end result being that it is somewhat easy to do. Look there and let me know. 😉

**Reply by PV-Joe** [reply]
Thanks for your reply, David!

This is a rather confusing thread for a non-programmer like me. This is why I thought this would fit nicely as an extra feature in your already excellent Solarman integration with just an input field for the AppKey and SystemID from PVoutput.org with all your standardised necessary sensor names preconfigured.

Never mind, if you are to busy with all the great work you've done already plus being busy keeping Solarman for Stick-Logger up to date and keeping it in shape.

This feature request is certainly not priority one but it could be nice for the Solarman Sick-Logger community to share and show off how efficient their solarsystems are in comparison.

As always, keep up the good work and maybe one day you get bored and want to spice up some functions this would be a great feature (if possible within your integration).

Joe

**Reply by davidrapan** [reply]
[Automations - PVOutput Uploader](https://github.com/davidrapan/ha-solarman/wiki/Automations#pvoutput-uploader)

**Reply by PV-Joe** [reply]
Graet, thank you.

I configured it with the code you provided and will check if the correct data will be uploaded with your suggested total sensor.

The updates seem to work already but there is no production yet.

This is a nice toy.
I'll keep you informed.

**Comment by PV-Joe** [comment, marked as answer]
The Yaml code did not upload but I figured out that this code works well.
Just add this to your configuration.yaml and don't forget to set your automation with the code in the second box.
Restart Home Asisstant.

```
#########################################
# PVoutput Upload | https://pvoutput.org
#########################################
rest_command:
  pvoutput_upload:
    url: https://pvoutput.org/service/r2/addstatus.jsp
    method: post
    content_type: "application/x-www-form-urlencoded"
    headers:
       X-Pvoutput-Apikey: <APIKEY HERE>
       X-Pvoutput-SystemId: <SYSTEM ID HERE>
    payload: "d={{now().strftime('%Y%m%d')}}&t={{now().strftime('%H:%M')}}&v1={{(states('sensor.solarman_today_production')|float*1000)|round(0)}}"

```

Here is the code for the automation that uploads to PVoutput.
10 min refresh works well with the "today_production" sensor.

```
alias: PVOutput Uploader
description: Uploads values to PVOutput
triggers:
  - minutes: /10
    trigger: time_pattern
conditions: []
actions:
  - data: {}
    action: rest_command.pvoutput_upload
mode: single
```
