### DISCUSSION TITLE
New device MAXGE (RETELEC) String Inverter

### DISCUSSION THREAD

**Discussion by javimagro** [davidrapan/ha-solarman#662] [Show and tell]
Hi, I have created a new yaml file to work with my MAXGE inverter. The MAXGE inverted model is MGEAKSI11 and serial number start with: 5203, firmware version: MW_08_8306_1.02

This is the code : 
```
#
# MGEA6KSI11
#
# 

default: 
  update_interval: 30
  code: 4
  digits: 6

parameters:
  - group: Inverter
    items:
      - name: "Product Model"
        rule: 5
        registers: [20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35]
      - name: "Serial Number"
        rule: 5
        registers: [60,61,62,63,64,65,66,67,68,69,70,71]
      - name: "Software Version"
        rule: 5
        registers: [44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59]

  - group: Load
    items:
      - name: "Load Power"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 3
        registers: [269,268]
        icon: "mdi:solar-power"

      - name: "Load Voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [264]
        icon: "mdi:transmission-tower"

      - name: "Load Current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [258]
        icon: "mdi:current-ac"

      - name: "Load Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [267]
        icon: "mdi:sine-wave"

  - group: Production
    items:
      - name: "Total Production"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        rule: 3
        registers: [276,275]
        icon: "mdi:solar-power"
        validation:
          min: 0.1

      - name: "Today Production"
        friendly_name: Today's Production
        update_interval: 300
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 1
        registers: [274,273]
        icon: "mdi:solar-power"

  - group: PV
    items:
      - name: "PV Power"
        class: "power"
        mppt: 1
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 3
        registers: [269,268]
        icon: "mdi:solar-power"

      - name: "PV1 Voltage"
        class: "voltage"
        mppt: 1
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [518]
        icon: "mdi:solar-power"

      - name: "PV1 Current"
        class: "current"
        mppt: 1
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [519]
        icon: "mdi:current-dc"

      - name: "PV1 Power"
        class: "power"
        mppt: 1
        state_class: "measurement"
        uom: "kW"
        rule: 1
        digits: 3
        registers: [518, 519]
        sensors:
          - registers: [518]
            scale: 0.1
          - operator: multiply
            scale: 0.0001
            registers: [519]

      - name: "PV2 Voltage"
        class: "voltage"
        mppt: 2
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [525]
        icon: "mdi:solar-power"

      - name: "PV2 Current"
        class: "current"
        mppt: 2
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [526]
        icon: "mdi:current-dc"

      - name: "PV2 Power"
        class: "power"
        mppt: 2
        state_class: "measurement"
        uom: "kW"
        rule: 1
        digits: 3
        registers: [525, 526]
        sensors:
          - registers: [525]
            scale: 0.1
          - operator: multiply
            scale: 0.0001
            registers: [526]
```
