### DISCUSSION TITLE
SOFAR 5KTLM-G3-A: Curtailment without a power meter (sofar_g3.yaml)

### DISCUSSION THREAD

**Discussion by scruysberghs** [davidrapan/ha-solarman#672] [Show and tell]
The existing Export Surplus Limitation is this :
```
  - group: Settings
    update_interval: 300
    items:
      - name: Export Surplus Limitation
        platform: select
        rule: 1
        registers: [0x1023]
        lookup:
          - key: 0x0000
            value: "Disabled"
          - key: 0x0001
            value: "Enabled"
          - key: 0x0002
            value: "Balanced"

      - name: Export Surplus Power
        platform: number
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 100
        rule: 1
        registers: [0x1024]
        range:
          min: 0
          max: 65535
````

I can't use these registers as I don't have a powermeter.

I did see that registers 1105 and 1106 allow you to enable/disable curtailment to a certain percentage.
Register 0x1106 (Active_Power_Export_Limit) – sets max export as 0.1% of nominal (0–1000).

Register 0x1105 (Power_Control) – enables/disables control and links the write to register 0x1106.
I have now added the 2 items to the settings block:
```
      - name: "Curtailment Enabled"
        platform: select
        rule: 1
        write: true
        registers: [0x1105]
        lookup:
          - key: 0x0000
            value: "Disabled"
          - key: 0x0001
            value: "Enabled"

      - name: "Curtailment Power Limit"
        platform: number
        class: "power"
        state_class: "measurement"
        uom: "%"
        scale: 0.1
        rule: 1
        write: true
        registers: [0x1106]
        range:
          min: 0
          max: 1000
```

I am able to curtail with this. For now only 0 or 100% so probably still something wrong with the scaling of the percentage?

Anyone else see a need for this? Should I make a PR for this?
