### DISCUSSION TITLE
Disable export

### DISCUSSION THREAD

**Discussion by SKeehnen** [davidrapan/ha-solarman#676] [Q&A] [answered]
Hi all,

I’m a happy user of this addon to control my Deye sun 12k sg04lp3-eu. 
There are two things I can’t find, maybe it’s just not possible.

1) How can I completely turn off the PV generation? So no export to grid and also not into the battery. I want to control this when there are negative energy prices.

2) I like the Zero export option, but it would be great if there is a Zero import option as well. Which will use the power from the battery to be used for the home consumption.

Thanks!

**Comment by sofkaski** [comment]
I have also Deye inverter (8k).

I have used the following simple automation to disable grid export when the spot price is negative and there is some forecasted production (`sensor.energy_current_hour` from [Open-Meteo Solar Forecast Integration](https://github.com/rany2/ha-open-meteo-solar-forecast)). It does not turn off the generation, but just the export. So any solar energy is still used in the house and to charge the battery. The inverter suppresses any extra PV.

```
alias: Grid Export Surplus
description: Export electricity surplus when non negative spot price
mode: single
triggers:
  - entity_id:
      - sensor.nordpool_kwh_fi_eur_4_095_0
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    trigger: state
conditions:
  - condition: numeric_state
    entity_id: sensor.energy_current_hour
    above: 0
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.nordpool_kwh_fi_eur_4_095_0
            below: 0
          - condition: state
            entity_id: switch.inverter_export_surplus
            state: "on"
        sequence:
          - metadata: {}
            data: {}
            target:
              entity_id: switch.inverter_export_surplus
            action: switch.turn_off
      - conditions:
          - condition: numeric_state
            entity_id: sensor.nordpool_kwh_fi_eur_4_095_0
            above: 0
          - condition: state
            entity_id: switch.inverter_export_surplus
            state: "off"
        sequence:
          - metadata: {}
            data: {}
            target:
              entity_id: switch.inverter_export_surplus
            action: switch.turn_on
```
