### DISCUSSION TITLE
Writing modbus registers

### DISCUSSION THREAD

**Discussion by amiko24** [davidrapan/ha-solarman#90] [Q&A]
Hello David, how can I write the registers.

I use such an automation to write the wallbox registers via Modbus. (See yaml code below).
Does it work the same way with the Deye Iverters?
What is the name of the hub for Deye sg04lp3? Slave number is 1 or 0?

`- id: '1680707528756'
  alias: Setze Ladestrom
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.output_strom_wallbox
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: modbus heidelberg wallbox
      address: 261
      slave: 1
      value:
      - '{{ (states.sensor.output_strom_wallbox.state) }}'`

**Comment by PV-Joe** [comment]
I don’t know about the write registers but:

Slave number is 1

… for my Deye SG04LP3

It works fine!

**Comment by gedger** [comment]
When I look at the services provided by solarman I only see.
![IMG_0263](https://github.com/user-attachments/assets/5efe1520-bc70-4a17-ac5a-10c3a94fdf6d)

**Comment by gedger** [comment]
So this is a working call to change a holding register.
![IMG_0264](https://github.com/user-attachments/assets/fad40587-507a-4fde-8b67-7a47f05ff139)

**Comment by amiko24** [comment]
it should also work via device

`   - action: solarman.write_holding_register
        metadata: {}
        data:
          wait_for_attempts: 5
          device: 70ddcba05b16bf94857f18e9836eb017
          register: 80
          value: 1
  mode: single``

**Comment by gedger** [comment]
It only works with device, the GUI translates the friendly device name to device id for you. if you look at the service call I showed above then the yaml is .

```
      - service: solarman.write_holding_register
        data:
          wait_for_attempts: 5
          device: db2d333f97371cec16797b695551cef5
          register: 3051
          value: 10000
```
