### DISCUSSION TITLE
Profile V2

### DISCUSSION THREAD

**Discussion by frsantos** [davidrapan/ha-solarman#92] [Ideas]
Hi @davidrapan 

I've been following the recent changes for name standardization, and as I've already created a profile myself for my inverter, I know how hard and repetitive task is to do it. Also, as you said in #73 

> And at the end I really don't care about the naming or simply how are the entities called. My only goal is to have the same name for entities with the same purpose (across all profile files) for clarity so it's easier and cleaner for people who are using several different devices (sure I'm now one of them so call me out for being a biased! 😆).

So, I've been thinking in a `V2` profile that is easier to fill. We know we all have more or less the same sensors/entities, some profiles have more, some have less, some have unique ones but most have the same and we can standardize most of the attributes of the common ones.

For example, we all have `PV Power` that is composed of 1 or more "PVn Power", so we can predefine some entities for all profiles and let the profile just fill in the gaps:

```yml
# Default profile: predefined entities in most profiles, only missing information about how to retrieve the data
version: 2

default:
  update_interval: 5
  # code: must be defined on profiles
  digits: 6

parameters:
  - group: pv
    name: 'Photovoltaic panels'
    power:
      # Not sure if this would be useful, but may the definition in the profile and the entity name should be different?      
      entity_name: pv_power 
      name: "PV Power"
      description: "Combined power of all inputs"
      update_frequency: realtime
      class: "power"
      state_class: "measurement"
      uom: "W"
      icon: "mdi:solar-power-variant"
      aggregate:
        # When an entity is composed of several items, how to name the others
        name: "PV#{index} Power"
        # By default sum all the item values, but we may need other complex operations
        operation: sum

    current:
      entity_name: pv_current
      name: "PV Current"
      update_frequency: realtime
      class: "current"
      state_class: "measurement"
      uom: "A"
      icon: "mdi:solar-power"
      aggregate:
        name: "PV#{index} Current"
        opearation: none # We don't need a total, just the items themselves

    voltage:      
      entity_name: "pv#{index}_voltage"
      name: ~ # No aggregation for voltage, just the individual panel values, so no aggregation entity is created
      update_interval: realtime
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      icon: "mdi:solar-power"
      aggregate:
        item_name: "PV#{index} Voltage"
        aggregation: none # We don't need a total, just the items themselves

  - group: inverter_info
    name: "Inverter information"
    serial_number: 
      entity_name: serial_number
      name: "Device Serial Number"
      update_frequency: 600
      class: ""
      state_class: "measurement"
      uom: ""
      icon: "mdi:wrench"
```

And then each profile would just fill in from and how the data is retrieved:

```yaml
# kstar profile
info:
  manufacturer: KSTAR
  model: Hybrid Inverter

default:
  update_interval: 20 # Overwrites default
  code: 0x04          # Specifies missing value in default
  # digits: 6         # Not defined, so it takes default                     

- parameters:
  - group: pv
    # Fill in missing information about pv_power
    pv_power:
      # All items have the same rule/scale
      rule: integer # Use names instead of codes to define rules, way more intuitive
      items:
        - registers: [3024]
        - registers: [3024]

    pv_current:
      items:
        # Each item have specific rule/scale
        - registers: [3024]
          rule: integer
          scale: 0.1
        - registers: [3024]
          rule: signed_integer
          scale: 0.01

    # pv_voltage not available on this profile, so no entity is defined

  - group: inverter_info
    serial_number:
        registers: [3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238]
        code: 0x03  # Define the function code for this data request
        rule: string

  # This profile has a very specific group of entities that can't be generalized into the default profile
  - group: my_specific_group
    my_entity:
      entity_name: my_entity
      name: "My specific inverter option"
      update_frequency: 20
      class: "class"
      state_class: "measurement"
      uom: "unit"
      icon: "mdi:icon"
      registers: [5000, 5001, 5002]
      rule: string
```

So, each profile would deep merge with the default profile to get the final profile, resulting in a very powerful profile definition while retaining a very standard list of entities for all profiles. Also, the default profile serves as documentation about what info is needed for a new profile.

Of course, this can integrate my other suggestion #48 about the inverter information to allow auto selecting the profile

What do you think?

**Comment by davidrapan** [comment]
Hey, first off it's nice to see someone taking the initiative on this standardization as it's not something where many see immediate value, haha. 😆 

_What I was doing so far was let's say mapping "the wide area" when comes to the sensors and find those which fulfills the same purpose, but have different naming._

**Your idea seems reasonable.** When I was thinking about it initially I thought of having the scheme hardcoded and then in the files just say what's there and what's not and in which registers +-.

Both implementation are great next stepping stone. But in the long run I would even try to do some sort of a register scanning to identify the device as you suggested in the #48 and then even locate registers but that would be very hard as the Solarman protocol, the Sticks and even modbus are real cr*p in my opinion and I' starting to hate this trio with every day more and more. 😆 

_But if that would be somewhat successful my end goal would be to satisfy requirements to be added as component of the HA but current implementation which is using those standalone files is everything but suitable for that._ 

That being said I'm currently writing small tools (scripts) for browsing the definition profiles all of them at once and looking for sensors with common names or even same registers to give us overview of the whole thing so when I'll be done it can be used to finish the design you started. 👍

**Reply by frsantos** [reply]
> Hey, first off it's nice to see someone taking the initiative on this standardization as it's not something where many see immediate value, haha. 😆

Yeah, you know the saying: "There are only two hard things in Computer Science..."
 

> _But if that would be somewhat successful my end goal would be to satisfy requirements to be added as component of the HA but current implementation which is using those standalone files is everything but suitable for that._

And what are the requirements, may I ask?

> 
> That being said I'm currently writing small tools (scripts) for browsing the definition profiles all of them at once and looking for sensors with common names

:+1: 

>  or even same registers

Do you think there can be common registers? I would say each system assigned the registers starting from scratch and there is no common ones.

> to give us overview of the whole thing so when I'll be done it can be used to finish the design you started. 👍


There are some improvements to the current profile schema that can be added incrementally, and then we can move to a more default one like this proposal. For example:

* Using a single `update_interval:` key for both `realtime` and a number (can be backwards compatible allowing both syntax for a while)
* Defining the `rule` by name instead of number (integer, string, ...) (also backwards compatible)
* Maybe the scale can be made more user friendly? Not sure
* `code` is also very generic and not descriptive enough (code for what?), maybe `function_code` to mimic the modbus terminology (Sebastian used `mb_fuction_code` which is still cryptic, but at least refers to modbus).
* `class`, `state_class`, `platform`: hard for a new user to differentiate among those. Maybe I'm still not too much into HA (still a lot to learn, solarman was the first I integrated), but I have a hard time to identify these, and I just copy/paste from one to another.

I don't know, maybe a good simple wiki page would help instead of renaming the keys, but still the code values would improve readability and bug spotting in the profiles.

One good thing about having a default profile is that we can group keys by purpose, without needing to repeat on each custom profile, only the default profile would be verbose but very descriptive. In the following example, more understandable though more verbose, we define the `entity` and `aggregate` in the default, and let the `source` be defined per profile.

```yml
    current:
      entity:
        id: pv_current
        name: "PV Current"
        icon: "mdi:solar-power"

        platform: "sensor"
        state_class: "measurement"
        class: "current"
        uom: "A"
        digits: 6

      aggregate:
        name: "PV#{index} Current"
        operation: none # We don't need a total, just the items themselves

      source:
        registers: [1, 2]
        function_code: 3
        rule: integer
        scale: 0.1
        update_frequency: realtime
```

And taking this even further, the default profile can be even split into different files for better organisation: 
```txt
schema/
  info.yml
  pv.yml
  inverter.yml
  battery.yml
  grid.yml
  status_and_errors.yml
```
They would be joined together into a single file for custom profile, though: `profiles.kstar_hybrid.yml`.
