### ISSUE TITLE
Switch on/off for microinverter doesn't work

### ISSUE THREAD

**Issue by terzo33** [davidrapan/ha-solarman#168]
Hi, @davidrapan , I tried to switch off my microinverter but doesn't work, nothing action.

![Screenshot_20240922_120640_Home Assistant.jpg](https://github.com/user-attachments/assets/e03c3a93-9d10-4836-89d5-a5ed754ded3b)

![Screenshot_20240922_120648_Home Assistant.jpg](https://github.com/user-attachments/assets/1266144b-8731-42f4-b87c-952a89bda7fd)

![Screenshot_20240922_120720_Home Assistant.jpg](https://github.com/user-attachments/assets/19fdc5e3-d165-47f9-aed4-b15c36f2ea4b)

![Screenshot_20240922_120858_Home Assistant.jpg](https://github.com/user-attachments/assets/4a432295-0ce6-4637-918a-802f2eac922f)

**Comment by davidrapan** [comment]
Hi @terzo33, please enabled debug logging and toggle the switch few times with sufficient time separation between each toggle ~ 30 seconds and attach the log file. Thanks!

**Comment by terzo33** [comment]
> Hi @terzo33, please enabled debug logging and toggle the switch few times with sufficient time separation between each toggle ~ 30 seconds and attach the log file. Thanks!

This is my log. Thanks

![home-assistant_debug.txt](https://github.com/user-attachments/files/17089889/home-assistant_debug.txt)

**Comment by davidrapan** [comment]
Try to edit the switch entity description in the file you are using like this:
```
      - name: ""
        platform: "switch"
        state_class: ""
        uom: ""
        scale: 1
        rule: 1
        registers: [0x002b]
        value:
          on: 0x0001
          off: 0x0002
```
And tell me if it changes anything. 😉
