### ISSUE TITLE
Add some new configurables for Deye (SUN-5K-SG03LP1)

### ISSUE THREAD

**Issue by rromrrom** [davidrapan/ha-solarman#177]
First of all I want to thank you for you really good integration. It works way more better than all I tried before. It cleans huge amount of pretty ugly customizations I had before.

I have deye hybrid Deye SUN-5K-SG03LP1. Here some more sensors which could be added to default deye_hybrid config.
Hope that helps.  

```
- group: Smart load
    items:

      - name: "Minimum solar power"
        platform: number
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x00F1]
        icon: 'mdi:solar-power'

      - name: "Grid Charge %"
        platform: number
        class: ""
        state_class: ""
        uom: "%"
        scale: 1
        rule: 1
        registers: [0x00E5]
        icon: 'mdi:home-lightning-bolt'

  - group: Peak shaving
    items:
      - name: "Gen peak shaving"
        class: "power"
        platform: number
        state_class: ""
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x0124]
        icon: 'mdi:generator-stationary'

      - name: "Grid peak shaving"
        class: "power"
        platform: number
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x0125]
        icon: 'mdi:transmission-tower'

  - group: system time
    items:
      - name: "System time"
        class: ""
        state_class: ""
        uom: ""
        scale: 1
        rule: 8
        registers: [0x0016,0x0017,0x0018]
```
