### ISSUE TITLE
Storage Control Mode selector for Solis Hybrid profile & write_holding_register query

### ISSUE THREAD

**Issue by stevebuk1** [davidrapan/ha-solarman#227]
I'm currently updating Pv_opt to interface to your new Solarman repo using a Solis inverter. 

It was originally written for StephenHuberts Solarman but writes to the modbus registers were never enabled. 
Pv_opt runs in Appdaemon so uses code along the following lines:

```
data = {"register": address, "value": value}
self.host.call_service("solarman/write_holding_register", **data)

```

I'm trying a simple write to the start time minutes register at 43144 but its not being reflected in the entity that reports the value. 
Setting the value on the inverter screen does update the entity, so its not a read issue. 

I've been looking at closed issues and see that along with the register number and the value to be written, there also needs to be a "device" set as well? If that isnt set, will that cause the issue? If so, where can I look it up from to use in an AppDaemon app? 

Note, I'm doing the PV_opt update on behalf of another user and I don't run Solarman myself, so am not able to easily try out different device settings, hence this query.

**Comment by davidrapan** [comment]
You need to know device id, you can discover it for example by trying run the action from developer tools (you select the device and then click on the GO TO YAML MODE button):
```
action: solarman.write_holding_register
data:
  wait_for_attempts: 30
  device: 68cc2dc7f6d70d4742dca1d660cba099
  register: 43144
  value: 1
```

**Comment by davidrapan** [comment]
But after thinking about it some more I really think that the best approach for you will be to rather use built-in HA action with entity as target:
```
action: time.set_value
target:
  entity_id: time.inverter_timed_charge_start
data:
  time: "06:30:00"
```

**Comment by stevebuk1** [comment]
Thanks for your support and quick responses.

Agreed for time registers, but hasn't gone down that route as still need to
write to the Solis storage control register, which in solis_hybrid.yaml is
a sensor and uses a modbus address which is read only.

Would it be simple to setup an entity to write to 43110 that uses the same
types? I think I'd need to use select rather than number?

**Comment by Pyinthesky99** [comment]
Hi David, thanks, setting wait_for_attempts to 30 worked a treat.

**Comment by davidrapan** [comment]
![solis_energy_storage_ctrl](https://github.com/user-attachments/assets/23409282-e2b2-420d-86c8-2064866f1ed7)

Are those bits mutually exclusive or do you need to control each separately?

**Comment by stevebuk1** [comment]
Individually, but there's only about 8 combinations. There are four hex
codes already in Solis_hybrid.yaml on the read-only sensor, so replicating
those four is fine.

**Comment by davidrapan** [comment]
Okay, I'll let you know when it's done. 😉

**Comment by stevebuk1** [comment]
Thanks so much!!

**Comment by davidrapan** [comment]
First draft:
```
      - name: Storage Control Mode
        platform: select
        rule: 1
        registers: [43110]
        lookup:
          - key: 0x0000
            value: "Disabled"
          - key: 0x0001
            value: "Self Use"
          - key: 0x0002
            value: "Optimized Revenue"
          - key: 0x0003
            value: "Time of Use"
          - key: 0x0004
            value: "Off-Grid"
          - key: 0x0008
            value: "Battery Wake-Up"
```
