### ISSUE TITLE
How can we read bits from registers

### ISSUE THREAD

**Issue by PitinoB** [davidrapan/ha-solarman#285]
![image](https://github.com/user-attachments/assets/185e5382-4978-4acd-add6-3981116a1113)

I need help with writing yaml code.
How can I read bits from registers?
Register 0x3104 return integer like 12610 or 12866.
I need to get values in table for that number.

Thanx

**Comment by davidrapan** [comment]
You can select specific bit with:
```
bit: {index}
```
added into entity description.

**Comment by PitinoB** [comment]
I dont know how to read bits from 0 to 4 and then get integer from 0 - 17 like in a table.
I tray with 
lookup:
  - bit; [0,1,2,3,4]

but not working

**Comment by davidrapan** [comment]
Show me full entity description and please don't forge to wrap the code block in \`\`\`{code}\`\`\`.

**Comment by PitinoB** [comment]
`  - group: Alarm-State
    items:
      - name: "DSP State"
        update_interval: 5
        class: "enum"
        rule: 1 # unsigned 16
        registers: [0x3104]
        bit: 2`

**Comment by PitinoB** [comment]
this reads single register and return value 0 or 1
but I want to read five registaers at once

**Comment by davidrapan** [comment]
Ah sure, I get it now! 😉 For that you need to use mask:
```
mask: 0x1F
```

**Comment by davidrapan** [comment]
And there is also another route you can take:
```
      - name: "Device Alarm"
        class: "enum"
        rule: 3
        registers: [0x0229, 0x022A]
        icon: "mdi:alert-outline"
        lookup:
          - key: 0
            value: "OK"
          - bit: [0, 1, 2, 3, 4]
            value: "{state_description}"
          - key: "default"
            value: "Error"
```
