### ISSUE TITLE
deye_micro - Device State Fault, when Inverter is working

### ISSUE THREAD

**Issue by V4n1X** [davidrapan/ha-solarman#342]
### Description

Deye SUN600G3-EU-230
Firmware: MW3_SSL_5408_1.0B

I don't use the additional Relay Box.

Solarman Device State show Fault (Value: 4), when the Inverter is working.
Solarman Device State show Normal (Value: 2), when the Inverter is online, but not working, due to low light conditions.

![image](https://github.com/user-attachments/assets/824fccb2-e9ac-411c-827e-7ed94c2765b7)

![image](https://github.com/user-attachments/assets/9a0394ac-cbe3-46e4-9cdc-bdd113ee2a9c)

So something seems off in the inverter defintion?
```
      - name: "Device State"
        class: "enum"
        rule: 1
        registers: [0x003B]
        icon: "mdi:state-machine"
        range:
          min: 0
          max: 5
        lookup:
          - key: 0x0000
            value: "Standby"
          - key: 0x0001
            value: "Self-test"
          - key: 0x0002
            value: "Normal"
          - key: 0x0003
            value: "Alarm"
          - key: 0x0004
            value: "Fault"
```

### Reproduction Steps

Inverter working -> Value 4
Inverter online, but not working due to low light -> 2
Other values, I don't have seem in the HA log.

### Log

I dont know what to post.

### Version

24.12.22

### Home Assistant Version

2024.12.5
