### ISSUE TITLE
Time synchronization

### ISSUE THREAD

**Issue by Xnyle** [davidrapan/ha-solarman#348]
### Is your feature request related to a problem?

Deye is pushing out updates that are potentially bricking inverters (no relays box despite no need / wrong country detected and so on)
So many people block internet access completely to forbid further updates.

In that case the inverter can not get the network time and so daily production can't reset.

### Describe the solution you'd like

But pvsolarman has a way to set the time as well via

"SunXG3RegistersWrite.DeviceTime(inv, datetime.datetime.now())"

Could that be implemented within the addon, maybe with an option switch to enable it?

### Describe alternatives you've considered

-

**Comment by davidrapan** [comment]
There is a way you can do it already and it's by using automation and setting Date & Time entity but there are some other ways currently coming (it's already part of latest code in this repo and just not yet released) and it's time synchronization using heartbeat time replies but it won't work for every inverter.

**Comment by Xnyle** [comment]
Thanks, but how? this doesn't seem to do anything, time entity not changing when triggered?
```
alias: Set Inverter Datetime
description: ""
triggers:
  - hours: "*"
    minutes: /5
    seconds: "5"
    trigger: time_pattern
conditions:
  - condition: and
    conditions:
      - condition: or
        conditions:
          - condition: time
            after: "06:30:00"
            before: "22:30:59"
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.inverter_device_state
        state: unavailable
actions:
  - data:
      datetime: "{{ now() }}"
    target:
      entity_id: datetime.inverter_date_time
    action: input_datetime.set_datetime
mode: single
```

**Comment by davidrapan** [comment]
Try to run this during debug logging enabled.

**Comment by Xnyle** [comment]
Referenced entities datetime.inverter_date_time are missing or not currently available

But thats the entities id name from the details?

**Comment by davidrapan** [comment]
Do you have this entity in the list of entities in device detail page?

**Comment by Xnyle** [comment]
Yes, in the "Configuration" section

**Comment by davidrapan** [comment]
Ah, it should be proly this action
```
action: datetime.set_value
```

**Comment by CrazyUs3r** [comment]
Is it necessary to change a setting on the inverter for the heartbeat? I just blocked the internet and it had no date or time. Writing about the action worked though

**Comment by davidrapan** [comment]
> Is it necessary to change a setting on the inverter for the heartbeat?

Not sure if it's enough honestly. It needs to be tested more and the packets has to be verified in server mode I guess.

**Comment by Skarabaen** [comment]
Deye can upgrade your firmware without your knowledge and currently do firmware upgrades which brick some devices. So I blocked the inverters from connecting the internet like @CrazyUs3r 
Unfortunately it seems that there are hardcoded ntp servers in the firmware, so without internet they can`t update the date and "Today Production" values don`t reset every day but sum up. I used the datetime.xxxxxx_date_time function to set the date manually. But it seems that it only triggers if you go to the webinterface of the inverter and press the restart button. After that the values "Today Production" values are set back to 0.

Can we set the somehow the ntp server with your addon?

**Comment by Xnyle** [comment]
I wouldn't advice to grant those devices any internet access at all now or even locally connect via the app (I guess that's how some got their updates forced)

```
actions:
  - data:
      datetime: "{{ now() }}"
    target:
      entity_id: datetime.inverter_date_time
    action: datetime.set_value
```

worked but as mentioned does not reset todays production
But that isn't really a problem as i will reset the next day so in essence it will reset every day except there it some very heavy cloud cover during the day.
