### ISSUE TITLE
Deye Hybrid SG04LP3: Wrong value for Total Production

### ISSUE THREAD

**Issue by PV-Joe** [davidrapan/ha-solarman#437]
Hi David,

I just realised that the value for Total Production is showing a lower value than within the official Solarman App with my old custom_configuration.yaml that is based on the old deye_sg04lp3.yaml.

Now I can't find the deye_sg04lp3.yaml anymore, so I think the configuration must have changed in one of the releases without me realising.

Here are the registers from my configuration:

```
      - name: "Total Production"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 3
        registers: [0x0216, 0x0217]
        icon: "mdi:solar-power"
        validation:
          min: 0.1
```

Could you please check and possibly advice me to the correct registers?
I tried the registers from your latest deye_hybrid.yaml but they show me even lower wrong values, so I'm confused how to solve the issue myself.

Thx ☀️

P.S:

I just tried reconfiguring selecting "auto". It didn't solve the wrong value for Total Production.
