### ISSUE TITLE
Deye: Add Off-grid switch

### ISSUE THREAD

**Issue by skajper4** [davidrapan/ha-solarman#493]
### Describe the solution you'd like

Hi. Could you add a switch to toggle offgrid option on deye_p3 config? Below is my working code.

```
  - group: Work Mode
    update_interval: 300
      - name: "Off Grid"
        platform: "select"
        rule: 1
        registers: [0x00B3]
        icon: "mdi:electric-switch"
        lookup:
          - key: 0x0000
            value: Auto
          - key: 0x0001
            value: Force
```

### Describe alternatives you've considered

.
