### ISSUE TITLE
Correction for "Today Consumption [kWh]" working for Deye Hybrid (deye_sg04lp3.yaml) - [Fault: Operator missing for subtraction]

### ISSUE THREAD

**Issue by PV-Joe** [davidrapan/ha-solarman#52]
Hi David,

I added your Custom Sensor for "Today's Consumption [kWh]" from your Wiki and realised that the operators for substraction were missing. The result was a much to high value as the values weren't substracted.

I tested the following YAML Code for the Custom Sensor (deye_sg04lp3.yaml) and it is working fine:

```
  - group: Custom Sensors
    items:
      # Calculates today's energy consumption
      # Formula: Today Energy Bought [0x0208] + Today Production [0x0211] + Today Battery Discharge [0x0203] - Today Energy Sold [0x0209] - Today Battery Charge [0x0202]
      - name: Today Consumption
        friendly_name: Today's Consumption
        alt: Daily Consumption
        description: Includes today's house consumption as well inverter consumption and AC/DC conversion losses
        class: energy
        state_class: total_increasing
        uom: kWh
        rule: 1
        digits: 1
        registers: [0x0208, 0x0211, 0x0203, 0x0209, 0x0202]
        sensors:
          - scale: 0.1
            registers: [0x0208]
          - scale: 0.1
            registers: [0x0211]
          - scale: 0.1
            registers: [0x0203]
          - operator: subtract
            scale: 0.1
            registers: [0x0209]
          - operator: subtract
            scale: 0.1
            registers: [0x0202]   
``` 
**Add this sensor for Deye Hybrid SG04LP3:**

1. Copy code to your "deye_sg04lp3.yaml" or "custom_configurations.yaml"
2. Restart Home Assistant
3. Add newly created sensor "sensor.solarman_today_consumption" to your dashboard

**Description:**
This Sensor will add a calculated value from today's house consumption as well inverter consumption and AC/DC conversion losses.
