### ISSUE TITLE
Suggestion: Add "Sell from Battery" Option in Work Mode

### ISSUE THREAD

**Issue by Zhyvotovskyy** [davidrapan/ha-solarman#583]
### Is your feature request related to a problem?

Hi David,

I have a suggestion to improve the “System Work Mode” configuration screen on the inverter.

Currently, in Sell mode, there is no way to control whether the battery is allowed to discharge into the grid. It would be very helpful to add an additional checkbox option like:

✅ Sell from Battery

This would allow users to precisely control when battery energy can be exported — for example, when operating under a Feed-in Tariff (Green Tariff) program.
If the box is checked, the battery is allowed to export energy to the grid. If unchecked, only PV surplus would be exported.

This would help reduce unnecessary battery cycling and give users better control over energy flow.

I’m happy to help with ideas or testing if needed.

Best regards,
Mykola

![Image](https://github.com/user-attachments/assets/52e0f37c-28d4-4d3d-ba94-711d323ed1f9)

### Describe the solution you'd like

Add an additional checkbox for "Sell from Battery" in the "System Work Mode" configuration.  
This would allow users to explicitly control whether the battery is allowed to discharge into the grid during Sell mode.

**Use case:**  
For users with a Feed-in Tariff (Green Tariff), it's useful to export from the battery only during specific hours to increase earnings and avoid unnecessary cycling of the battery.

If checked — the battery is allowed to export energy.  
If unchecked — only PV surplus will be sold to the grid.

### Describe alternatives you've considered

Currently, there is no direct way to prevent or allow battery export in Sell mode based on time.  
Some users are using indirect workarounds through time-of-use charging settings, but they are not reliable or intuitive.

An explicit checkbox would greatly improve control and clarity for end users.

**Comment by rolupusoru** [comment]
To  my knowledge if you want to discharge battery  into grid, then you need to set your inverter on "Seling first" under System Work Mode first page. Then on time of use you set the interval and battery % you want your the inverter to discharge. 

In your example, with this setup, you inverter would discharge the battery down to 55% between 6-11 in the morning and again between 18-23. the rest of the time it will look for power to charge you batteries back to 100%. Because you also have grid charge set, it will also take power from grid to charge them. If you uncheck grid charge, then inverter will only charge from solar if available.

**Comment by Zhyvotovskyy** [comment]
Hi David,

Thank you for your detailed explanation — it helped clarify the inverter
logic.

I’d like to kindly suggest a small but very useful addition to your
integration. In my setup, I often need to *dynamically enable or disable
battery discharge to the grid*, depending on the current situation.

For example, during an *air raid alert in Ukraine*, I *disable battery
export* to preserve charge in case of a sudden blackout. When the situation
is calm ("clear skies" — both literally and figuratively), I allow the
battery to discharge to the grid again. Being able to control this through
Home Assistant would make this much easier and safer.

There’s also another reason. My *inverter is 50 kW*, but I’m only allowed
to *export 30 kW*. That means I need to intelligently *balance* battery
usage: charge the battery during solar peak, and discharge it later when
solar output drops. In summer and winter, my logic is different — so *automated
control is essential*.

At the moment, I can manage everything from Home Assistant — except for
toggling that critical checkbox to allow battery discharge to the grid. I
still have to do that manually through the mobile app.

Would it be possible to expose that option as a switch or setting in the
integration? I’d be happy to assist with testing or documentation if needed.

Thank you again for your great work!

Best regards,
Mykola from Ukraine

вт, 13 мая 2025 г. в 18:44, rolupusoru ***@***.***>:

**Comment by Adminius** [comment]
> ![Image](https://github.com/user-attachments/assets/52e0f37c-28d4-4d3d-ba94-711d323ed1f9)

Which inverter and firmware do you have?

**Comment by andriiko78** [comment]
Hello.
My inverter Deye SUN-50K also has these menu items.
Firmware version MAIN：3103-1095-1E08

**Comment by andriiko78** [comment]
> Привіт, Девіде, дякую за твою роботу над інтеграцією ha-solarman. Просто хотів повідомити, що після оновлення до версії *v25.05.20*, інтеграція втратила зв'язок з інвертором. Ми повернулися до *v25.05.12*, і все знову працює добре. Будь ласка, повідом мене, якщо тобі потрібні якісь логи або допомога в тестуванні. З найкращими побажаннями, Микола, пт, 23 травня 2025 р. о 11:36, andriiko78 ***@***.***>:
> […](#)

I have a similar problem. The latest version of the program does not read data from the inverter.

**Comment by davidrapan** [comment]
Can someone provide debug log from latest version?

**Comment by Zhyvotovskyy** [comment]
Hi David,

Today I noticed two strange parameters in the inverter integration:

   -

   Grid Max Export Power – showing a value of 50000
   -

   Grid Max Import Power – currently empty

These parameters do not exist in the inverter’s native interface (either
on-screen or in the official web portal), so I’m wondering where they come
from. Could they be placeholders or misinterpreted registers?

Thank you in advance for your clarification!

Best regards,
Mykola

пт, 23 мая 2025 г. в 16:32, Микола Животовський ***@***.***>:

**Comment by davidrapan** [comment]
Hi, @Zhyvotovskyy, these are documented in Modbus RTU documentation.

**Comment by Zhyvotovskyy** [comment]
Hi David,

I’d like to report an issue with scaling in the deye_p3.yaml profile for
Deye inverters (SG0*HP3).

For a long time I didn’t pay much attention to some energy-related values
in Home Assistant, because I usually monitored them in the original
Solarman app. Only recently I noticed that several values in HA are
consistently *10× lower than the real ones*.

Examples include:

   -

   Battery charge / discharge (today)
   -

   Energy import / export (today)
   -

   Some other daily energy counters

After checking the raw data and comparing it with the Solarman app, it’s
clear that the inverter reports correct values, but the YAML profile
applies an incorrect ×0.1 scaling for these sensors.

Important detail:

   -

   For calculated sensors using rule: 0, the scale parameter is ignored, so
   this cannot be corrected on the user side.
   -

   Because of that, users cannot reliably fix these values without
   modifying the YAML profile itself.

I’ve already corrected the scaling in my local copy of deye_p3.yaml and I’m
attaching it to this message as a reference. The changes fix the 10×
underreporting and bring HA values in line with the Solarman app.

I believe this is a profile-level issue rather than a configuration
mistake, so it would be great if the scaling could be reviewed and fixed
upstream.

If you need any additional details, logs, or comparisons — just let me know.

Thanks again for your work on this project.

Best regards,
Mykola


чт, 5 июн. 2025 г. в 15:07, David Rapan ***@***.***>:

**Comment by davidrapan** [comment]
Hi @Zhyvotovskyy, it's discussed in #782 and it's most likely a bug in the firmware == even values in the Solarman App are prolly incorrect.

**Comment by StRobiEst** [comment]
> Currently, in Sell mode, there is no way to control whether the battery is allowed to discharge into the grid. It would be very helpful to add an additional checkbox option like:
> 
> ✅ Sell from Battery
> 
> This would allow users to precisely control when battery energy can be exported — for example, when operating under a Feed-in Tariff (Green Tariff) program. If the box is checked, the battery is allowed to export energy to the grid. If unchecked, only PV surplus would be exported.

I changed the deye_p3.yaml file profile to add selling to TOU for all 6 programming instances.

From: 
```
      - name: Program 1 Charging
        platform: select
        rule: 1
        registers: [0x00AC]
        icon: mdi:sun-clock
        lookup:
          - key: 0x0000
            value: "Disabled"
          - key: 0x0001
            value: "Grid"
          - key: 0x0002
            value: "Generator"
          - key: 0x0003
            value: "Both"
```

To:
```
      - name: Program 1 Charging
        platform: select
        rule: 1
        registers: [0x00AC]
        icon: mdi:sun-clock
        lookup:
          - key: 0x0000
            value: "Disabled"
          - key: 0x0001
            value: "Grid"
          - key: 0x0002
            value: "Generator"
          - key: 0x0003
            value: "Grid+Gen"
          - key: 0x0020
            value: "Sell"
          - key: 0x0021
            value: "Grid+Sell"
          - key: 0x0022
            value: "Gen+Sell"
          - key: 0x0023
            value: "All"
```
