### ISSUE TITLE
INVT XG: Device profile extension

### ISSUE THREAD

**Issue by Nicomagno** [davidrapan/ha-solarman#584]
I made a description file for INVT 110XG inverter.

I have tested it for a year.
with a previous version of the ha-solarman repository that wasn't maintained anymore.
just found yours that is being actively worked on. 

The description file works fine, just need to manually add it after every update.

Can the file be added to the repository, so others can use it?

compressed .yaml Description File:
[INVT_110XG.zip](https://github.com/user-attachments/files/20187932/INVT_110XG.zip)

parameter list from the vendor:
[INVT XG&XD Inverter Modbus RTU Protocol(3).pdf](https://github.com/user-attachments/files/20188053/INVT.XG.XD.Inverter.Modbus.RTU.Protocol.3.pdf)

```
# INVT XG110 on-grid inverter
# LSW - 5 Wifi Loger with firmware LSW5BLE_17_8420_1.24

requests:
 - start: 0x3806
   end:  0x3859
   mb_functioncode: 0x03
 - start: 0x3873
   end:  0x388E
   mb_functioncode: 0x03
 - start: 0x3018
   end:  0x301A
   mb_functioncode: 0x03
parameters:
 - group: control
   items:
    - name: "Percent of active Power"
      class: ""
      state_class: "measurement"      
      uom: "%"
      scale: 0.1
      rule: 1 
      registers: [0x3019]
      icon: 'mdi:power-settings'
 - group: solar
   items: 
    - name: "PV01 Voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1 
      registers: [0x3836]
      icon: 'mdi:solar-power'

    - name: "PV01 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3837]
      icon: 'mdi:solar-power'  

    - name: "PV02 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3838]
      icon: 'mdi:solar-power'      

    - name: "PV02 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3839]
      icon: 'mdi:solar-power' 

    - name: "PV03 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x383A]
      icon: 'mdi:solar-power'      

    - name: "PV03 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x383B]
      icon: 'mdi:solar-power'

    - name: "PV04 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x383C]
      icon: 'mdi:solar-power'      

    - name: "PV04 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x383D]
      icon: 'mdi:solar-power'

    - name: "PV05 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x383E]
      icon: 'mdi:solar-power'      

    - name: "PV05 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x383F]
      icon: 'mdi:solar-power'

    - name: "PV06 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3840]
      icon: 'mdi:solar-power'      

    - name: "PV06 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3841]
      icon: 'mdi:solar-power'    

    - name: "PV07 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3842]
      icon: 'mdi:solar-power'      

    - name: "PV07 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3843]
      icon: 'mdi:solar-power'   

    - name: "PV08 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3844]
      icon: 'mdi:solar-power'      

    - name: "PV08 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3845]
      icon: 'mdi:solar-power'   

    - name: "PV09 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3846]
      icon: 'mdi:solar-power'      

    - name: "PV09 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3847]
      icon: 'mdi:solar-power'   

    - name: "PV10 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3848]
      icon: 'mdi:solar-power'      

    - name: "PV10 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3849]
      icon: 'mdi:solar-power'   

    - name: "PV11 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x384A]
      icon: 'mdi:solar-power'      

    - name: "PV11 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x384B]
      icon: 'mdi:solar-power'   

    - name: "PV12 Voltage"
      class: "voltage"    
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x384C]
      icon: 'mdi:solar-power'      

    - name: "PV12 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x384D]
      icon: 'mdi:solar-power'           

    - name: "Daily Production"
      class: "energy"
      state_class: "total_increasing"      
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x382F]
      icon: 'mdi:solar-power'      

    - name: "Total Production"
      class: "energy"
      state_class: "total"      
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x3831,0x3830]
      icon: 'mdi:solar-power'      

    - name: "Total generation time"
      class: ""
      state_class: "measurement"      
      uom: "s"
      scale: 0.5
      rule: 3
      registers: [0x382E,0x382D]
      icon: 'mdi:clock-outline'  

    - name: "Derated Power"
      class: ""
      state_class: "measurement"      
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [0x3829,0x382A]
      icon: 'mdi:gauge'    

 - group: Output
   items: 
    - name: "Output active power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 0.1
      rule: 4
      registers: [0x381E,0x381D]
      icon: 'mdi:home-lightning-bolt'

    - name: "Output reactive power"
      class: ""
      state_class: "measurement"      
      uom: "Var"
      scale: 0.1
      rule: 4
      registers: [0x3820,0x381F]
      icon: 'mdi:home-lightning-bolt'

    - name: "Grid frequency"
      class: "frequency"
      state_class: "measurement"      
      uom: "Hz"
      scale: 0.01
      rule: 1
      registers: [0x381A]
      icon: 'mdi:home-lightning-bolt'

    - name: "L1 Voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3811]
      icon: 'mdi:home-lightning-bolt'

    - name: "L1 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x3817]
      icon: 'mdi:home-lightning-bolt'

    - name: "L2 Voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3812]
      icon: 'mdi:home-lightning-bolt'

    - name: "L2 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x3818]
      icon: 'mdi:home-lightning-bolt'

    - name: "L3 Voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3813]
      icon: 'mdi:home-lightning-bolt'

    - name: "L3 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x3819]
      icon: 'mdi:home-lightning-bolt'
    
    - name: "Leakage Current"
      class: "current"
      state_class: "measurement"      
      uom: "mA"
      scale: 0.1
      rule: 1
      registers: [0x3829]
      icon: 'mdi:home-lightning-bolt'

    - name: "R Phase Current"
      class: "current"
      state_class: "measurement"      
      uom: "mA"
      scale: 0.1
      rule: 2
      registers: [0x3832]
      icon: 'mdi:home-lightning-bolt'

    - name: "S Phase Current"
      class: "current"
      state_class: "measurement"      
      uom: "mA"
      scale: 0.1
      rule: 2
      registers: [0x3833]
      icon: 'mdi:home-lightning-bolt'

    - name: "T Phase Current"
      class: "current"
      state_class: "measurement"      
      uom: "mA"
      scale: 0.1
      rule: 2
      registers: [0x3834]
      icon: 'mdi:home-lightning-bolt'
    
    - name: "DC Isolation Resistance"
      class: ""
      state_class: "measurement"      
      uom: "kOhm"
      scale: 1
      rule: 1
      registers: [0x3835]
      icon: 'mdi:home-lightning-bolt'

    - name: "String01 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x384E]
      icon: 'mdi:grid'  
    
    - name: "String03 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x384F]
      icon: 'mdi:grid'  

    - name: "String05 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3850]
      icon: 'mdi:grid'  

    - name: "String07 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3851]
      icon: 'mdi:grid'  

    - name: "String09 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3852]
      icon: 'mdi:grid'  

    - name: "String11 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3853]
      icon: 'mdi:grid'  

    - name: "String13 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3854]
      icon: 'mdi:grid'  

    - name: "String15 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3855]
      icon: 'mdi:grid'  

    - name: "String17 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3856]
      icon: 'mdi:grid'  

    - name: "String19 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3857]
      icon: 'mdi:grid'  

    - name: "String21 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3858]
      icon: 'mdi:grid'  

    - name: "String23 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3859]
      icon: 'mdi:grid'  

    - name: "String02 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3873]
      icon: 'mdi:grid'  

    - name: "String04 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3874]
      icon: 'mdi:grid'  

    - name: "String06 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3875]
      icon: 'mdi:grid'  

    - name: "String08 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3876]
      icon: 'mdi:grid'

    - name: "String10 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3877]
      icon: 'mdi:grid'

    - name: "String12 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3878]
      icon: 'mdi:grid'

    - name: "String14 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x3879]
      icon: 'mdi:grid' 

    - name: "String16 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x387A]
      icon: 'mdi:grid' 

    - name: "String18 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x387B]
      icon: 'mdi:grid'

    - name: "String20 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x387C]
      icon: 'mdi:grid'   

    - name: "String22 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x387D]
      icon: 'mdi:grid' 

    - name: "String24 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x387E]
      icon: 'mdi:grid' 

 - group: Inverter
   items: 
    - name: "Inverter status"
      class: ""
      state_class: "measurement"      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3806]
      lookup: 
      -  key: 0
         value: "Initialization"
      -  key: 1
         value: "Stand-by"
      -  key: 2
         value: "Normal"
      -  key: 3
         value: "FAULT"
      -  key: 4
         value: "Programing"
      -  key: 5
         value: "OFF grid"
      icon: 'mdi:wrench'         

    - name: "Inverter module R temperature"
      class: "temperature"
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x3822]
      icon: 'mdi:thermometer'
   
    - name: "Inverter module S temperature"
      class: "temperature"
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x3823]
      icon: 'mdi:thermometer'
   
    - name: "Inverter module T temperature"
      class: "temperature"
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x3824]
      icon: 'mdi:thermometer'

    - name: "Inverter Heatsink temperature"
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x3826]
      icon: 'mdi:thermometer'

    - name: "Inverter Ambient temperature"
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x3825]
      icon: 'mdi:thermometer'      

    - name: "Nbus voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x380F]
      icon: 'mdi:home-lightning-bolt'

    - name: "Pbus voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x3810]
      icon: 'mdi:home-lightning-bolt'

    - name: "Countdown time"
      class: ""
      state_class: "measurement"      
      uom: "s"
      scale: 1
      rule: 1
      registers: [0x381B]
      icon: ''

    - name: "Inverter efficiency"
      class: ""
      state_class: "measurement"      
      uom: "%"
      scale: 0.1
      rule: 1
      registers: [0x3882]
      icon: 'mdi:PercentOutline'

    - name: "RTC status"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3883]
      icon: 'mdi:WebClock'
      lookup: 
      -  key: 0
         value: "No RTC"
      -  key: 1
         value: "RTC configured"

    - name: "Communication quality"
      class: ""
      state_class: "measurement"      
      uom: "%"
      scale: 0.1
      rule: 1
      registers: [0x3884]
      icon: 'mdi:WifiStar'

 - group: Alert
   items: 
    - name: "Alarm code"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 3
      registers: [0x3808,0x3807]

    - name: "Alarm bit"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 3
      registers: [0x380C,0x380B]

    - name: "Alarm main code"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3807]

    - name: "Alarm Type"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3807]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "Fan speed alarm"
      -  key: 2
         value: "Lightning protector"
      -  key: 3
         value: "String current alarm"
    
    - name: "Alarm sub code"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3808]

    - name: "Alarm"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 3
      registers: [0x3808,0x3807]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 65537
         value: "ID 01-01 FAN 1"
      -  key: 65538
         value: "ID 01-02 FAN 2"
      -  key: 65539
         value: "ID 01-03 FAN 3"
      -  key: 65540
         value: "ID 01-04 FAN 4"
      -  key: 65541
         value: "ID 01-05 FAN 5"
      -  key: 65542
         value: "ID 01-06 FAN 6"
      -  key: 65543
         value: "ID 01-07 FAN 7"
      -  key: 65544
         value: "ID 01-08 FAN 8"
      -  key: 65545
         value: "ID 01-09 FAN 9"
      -  key: 65546
         value: "ID 01-10 FAN 10"
      -  key: 131073
         value: "ID 02-01 Ligning Protection"
      -  key: 196609
         value: "ID 03-01 String 1"
      -  key: 196610
         value: "ID 03-02 String 2"
      -  key: 196611
         value: "ID 03-03 String 3"
      -  key: 196612
         value: "ID 03-04 String 4"
      -  key: 196613
         value: "ID 03-05 String 5"
      -  key: 196614
         value: "ID 03-06 String 6"
      -  key: 196615
         value: "ID 03-07 String 7"
      -  key: 196616
         value: "ID 03-08 String 8"
      -  key: 196617
         value: "ID 03-09 String 9"
      -  key: 196618
         value: "ID 03-10 String 10"
      -  key: 196619
         value: "ID 03-11 String 11"
      -  key: 196620
         value: "ID 03-12 String 12"
      -  key: 196621
         value: "ID 03-13 String 13"
      -  key: 196622
         value: "ID 03-14 String 14"
      -  key: 196623
         value: "ID 03-15 String 15"
      -  key: 196624
         value: "ID 03-16 String 16"
      -  key: 196625
         value: "ID 03-17 String 17"
      -  key: 196626
         value: "ID 03-18 String 18"
      -  key: 196627
         value: "ID 03-19 String 19"
      -  key: 196628
         value: "ID 03-20 String 20"
      icon: 'mdi:alert'  

    - name: "Fault code"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 3
      registers: [0x380A,0x3809]

    - name: "Fault bit"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 3
      registers: [0x380E,0x380D]

    - name: "Fault main code"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3809]

    - name: "Fault Type"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x3809]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "PV Voltage fault"
      -  key: 3
         value: "BUS Voltage error"
      -  key: 5
         value: "Flow Failure"
      -  key: 6
         value: "Thermal fault"
      -  key: 7
         value: "Insulation fault"
      -  key: 8
         value: "Drive fault"
      -  key: 9
         value: "Communication fault"
      -  key: 10
         value: "Leakage Current fault"
      -  key: 11
         value: "Relay fault"
      -  key: 14
         value: "DCI fault"
      -  key: 19
         value: "Consistency Test fault"
      -  key: 31
         value: "Mains Voltage fault"
      -  key: 33
         value: "Mains Frequency fault"
      -  key: 37
         value: "Leakage Current self check fault"
      -  key: 45
         value: "Auxiliary power fault"
     
    - name: "Fault sub code"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x380A]

    - name: "Fault"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 3
      registers: [0x380A,0x3809]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 65537
         value: "ID 01-01 PV Electricity Down"
      -  key: 65538
         value: "ID 01-02 PV Voltage High"
      -  key: 196609
         value: "ID 03-01 BUS Voltage Low"
      -  key: 196610
         value: "ID 03-02 BUS Voltage High"
      -  key: 196611
         value: "ID 03-03 BUS Voltage Imbalance"
      -  key: 327681
         value: "ID 05-01 Inverter Hardware Fault"
      -  key: 327682
         value: "ID 05-02 Inverter Software Fault"
      -  key: 327683
         value: "ID 05-02 Inverter BOOST Hardware Fault"
      -  key: 393217
         value: "ID 06-01 Inverter Temperature"
      -  key: 393218
         value: "ID 06-02 Inverter BOOST Temperature"
      -  key: 393219
         value: "ID 06-03 Heatsink Temperature"  
      -  key: 393220
         value: "ID 06-04 Ambient Temperature"
      -  key: 458753
         value: "ID 07-01 Insulation Fault"
      -  key: 524289
         value: "ID 08-01 Drive Fault"
      -  key: 589825
         value: "ID 09-01 DSP1 - ARM SCI Comm Fault"
      -  key: 589826
         value: "ID 09-02 DSP2 - ARM SCI Comm Fault"
      -  key: 589827
         value: "ID 09-03 DSP1 - SPI Comm Fault"
      -  key: 589828
         value: "ID 09-04 DSP2 - SPI Comm Fault"
      -  key: 589828
         value: "ID 09-05 SCI - MCU Comm Fault"
      -  key: 655361
         value: "ID 10-01 Current Leakage"
      -  key: 655362
         value: "ID 10-02 30mA Current Leakage"
      -  key: 655363
         value: "ID 10-03 60mA Current Leakage"
      -  key: 655364
         value: "ID 10-04 150mA Current Leakage"
      -  key: 720897
         value: "ID 11-01 Open Circuit"
      -  key: 720898
         value: "ID 11-02 Short Circuit"
      -  key: 917505
         value: "ID 14-01 DCI R pfase Fault"
      -  key: 917506
         value: "ID 14-02 DCI S pfase Fault"
      -  key: 917507
         value: "ID 14-03 DCI T pfase Fault"
      -  key: 1245185
         value: "ID 19-01 AC Voltage Consistency Fault"
      -  key: 1245186
         value: "ID 19-02 BUS Voltage Consistency Fault"
      -  key: 1245187
         value: "ID 19-03 ISO Voltage Consistency Fault"
      -  key: 1245188
         value: "ID 19-04 PV Voltage Consistency Fault"
      -  key: 1245189
         value: "ID 19-05 GFCI Voltage Consistency Fault"
      -  key: 2031620
         value: "ID 31-01 Mains Voltage Low"
      -  key: 2031617
         value: "ID 31-02 Mains Voltage High"
      -  key: 2162689
         value: "ID 33-01 Mains Frequency Low"
      -  key: 2162690
         value: "ID 33-01 Mains Frequency Low"
      -  key: 2424833
         value: "ID 37-01 Remote Shutdown"
      -  key: 2818049
         value: "ID 43-01 Current Leakage sensor Fault"
      -  key: 2949121
         value: "ID 45-01 Auxiliary Power OFF"

      icon: 'mdi:alert-octagon'  

    - name: "Derating Mode"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x382C]
      lookup: 
      -  key: 0
         value: "No Derating"
      -  key: 1
         value: "Ambient Temperature High"
      -  key: 2
         value: "Over frequency Derating"
      -  key: 3
         value: "Reactive Power Derating"
      -  key: 4
         value: "User-set Active Power Derating"
      -  key: 5
         value: "Load slope Derating"
      -  key: 6
         value: "Fan Derating"
      -  key: 7
         value: "Wave by Wave Derating"
      -  key: 8
         value: "export Limit"
      -  key: 9
         value: "Low penetration Derating"
      -  key: 10
         value: "reset MPPT Derating"
      -  key: 12
         value: "BUS voltage Limit"
      icon: 'mdi:wrench' 
```
