### ISSUE TITLE
ZCS Azzurro HYD 3/6k ZSS HP loses entities with Sofar G3 profile

### ISSUE THREAD

**Issue by gmcinalli** [davidrapan/ha-solarman#643]
### Description

Hi, I have a **ZCS Azzurro HYD 3/6k ZSS HP** with 4 batteries, before I used the inverter definition `zcs_azzurro-hyd-zss-hp.yaml` and it worked perfectly.

With the release of [v25.06.02](https://github.com/davidrapan/ha-solarman/releases/tag/v25.06.02), I switched to `sofar_g3.yaml` selecting battery packs 1 as stated [here](https://github.com/davidrapan/ha-solarman/wiki/Supported-Devices) but some entities disappeared, for example the section with _"Device Serial Number"_ or _"Device Fault"_ are no longer shown.

Looking in the yaml files the registry values ​​of the previous file and current one match, why the entities do not appear anymore?

Before I had about 68 entities, now only 50.

### Reproduction Steps

Update to [v25.06.02](https://github.com/davidrapan/ha-solarman/releases/tag/v25.06.02) and use `sofar_g3` profile with ZCS Azzurro HYD 3/6k ZSS HP.

### Log

[home-assistant_solarman_2025-06-05T08-09-03.331Z.log](https://github.com/user-attachments/files/20605662/home-assistant_solarman_2025-06-05T08-09-03.331Z.log)

### Version

v25.06.02

### Home Assistant Core Version

2025.5.3

### Home Assistant Operating System Version

15.2

**Comment by davidrapan** [comment]
Hi @gmcinalli, `['Device Hardware Version', 'Device Software Version Master', 'Device Software Version Slave', 'Device Safety Version', 'Device Safety Firmware Version', 'Device Safety Hardware Version']` are now attributes attached to Device State sensor.

Are you sure that Device Fault is missing?

**Comment by gmcinalli** [comment]
@davidrapan Oh, I think you're right.

![Image](https://github.com/user-attachments/assets/5d7f6e3f-ffa9-47cc-b3eb-d4b2fc6d474a)

Also the Device Fault section is here.

![Image](https://github.com/user-attachments/assets/4e894ce4-6a1d-4187-8749-801dedd943dc)

But then how did I get from 68 entities to 50, what else is missing or has been merged?

**Comment by gmcinalli** [comment]
@davidrapan `Battery EPS Buffer`, `Battery EOD`, `Battery DOD` are some examples of missing entities that before were present.

```yaml
      - name: "Battery DOD"
        update_interval: 30
        state_class: "measurement"
        uom: "%"
        rule: 1
        registers: [0x104D]
        icon: "mdi:battery"

      - name: "Battery EOD"
        update_interval: 30
        state_class: "measurement"
        uom: "%"
        rule: 1
        registers: [0x104E]
        icon: "mdi:battery"

      - name: "Battery EPS Buffer"
        update_interval: 30
        state_class: "measurement"
        uom: "%"
        rule: 1
        registers: [0x1052]
        icon: "mdi:battery-low"
```
