### ISSUE TITLE
All power values are wong scaled for ZCS Azzurro HYD 3/6k ZSS

### ISSUE THREAD

**Issue by Dieghito72** [davidrapan/ha-solarman#649]
All power values are wong scaled for [ZCS Azzurro HYD 3/6k ZSS](https://www.zcsazzurro.com/inverter/azzurro-hybrid-storage-inverter-hyd-hyd-3000-zss-hyd-6000-zss)

I noticed that they have been scaled from  **0.01** to **0.00001** in last commit of sofar_wifikit, maybe config for scale modifier is missing ?

**Comment by davidrapan** [comment]
Hi @Dieghito72, yes it’s wrong. It should have been the other way around. I noticed too late.

**Comment by davidrapan** [comment]
[fix: Scaling of power entities in Sofar Wifikit](https://github.com/davidrapan/ha-solarman/commit/aa75d3ebb3f748b6f6e0fe46c7fc69186b2ffe45)

**Comment by Dieghito72** [comment]
> [fix: Scaling of power entities in Sofar Wifikit](https://github.com/davidrapan/ha-solarman/commit/aa75d3ebb3f748b6f6e0fe46c7fc69186b2ffe45)

Hi @davidrapan, just tried the last preset, but maybe some adjustments are necessary also for validation:

pv_power_sensor: 990 validation failed. Conditions: {'min': 0, 'max': 50, 'invalidate_all': None}

Since I have some production peak to more that 6kW, this is what i tried (after this change everithing seems to be OK):

```yaml
    items:
      - name: "PV Power"
        class: "power"
        mppt: 1
        state_class: "measurement"
        uom: "W"
        scale: 10
        rule: 1
        registers: [0x0215]
        validation:
          min: 0
          max: 7000
          invalidate_all:
        icon: "mdi:solar-power-variant"
```

Thanks for your work.
