### ISSUE TITLE
Off Grid power limitation sensor

### ISSUE THREAD

**Issue by alex-military** [davidrapan/ha-solarman#682]
### Is your feature request related to a problem?

hello guys find all this fantastic, hk a 10K hybrid three-phase sun and it works perfectly, and a bit cumbersome to configure some dashboard tabs in fact I have problems creating the graphs especially the second and third, for the weather data not present (I can't understand where to get them from, maybe I skipped some steps?), and for some indentation errors in the configuration code copied from here and reported so it must be inserted and moved line by line.

anyway having an Off Grid system I wanted to know if there is a way to know when the inverter is limiting its power because the batteries are charged and the production exceeds consumption so as to create an activation automation and loads such as air conditioners and others.

can you explain to me how to do it because I wasted the morning and I didn't understand a thing then it is my first configuration of home Assistant and I'm trying to learn little by little with the help of gpt chat

I'm waiting for someone who can give info on the dashboard graphs and on this "sensor" to activate the loads automatically

### Describe the solution you'd like

Activation of loads when production exceeds consumption

### Describe alternatives you've considered

.

**Comment by davidrapan** [comment]
Hi @alex-military,

> for the weather data not present

If you mean PV forecast data then you need solcast integration from HACS or GitHub.

> I wanted to know if there is a way to know when the inverter is limiting its power

I don't think there's a way to know (but I think there should be, though, because it's a good point). The only way I can think of right now is to treat 95%+ (or 99%+, if you want to be extra precise) with a combination of no power draw on batteries as your trigger.

**Comment by alex-military** [comment]
hello, I had already installed solarcast but in fact the problem was in the name of the sensors that are indicated here in English while he inserted them in Italian. now I managed to complete at least the first graph. now I have problems with the other 2 I will try to understand at most I will ask for help.

for the moment I am struggling with the layout because even if I set the card in the dashboard to the maximum size it always remains very narrow and I do not understand how to solve it.

**Comment by alex-military** [comment]
> Hi [@alex-military](https://github.com/alex-military),
> 
> > for the weather data not present
> 
> If you mean PV forecast data then you need solcast integration from HACS or GitHub.
> 
> > I wanted to know if there is a way to know when the inverter is limiting its power
> 
> I don't think there's a way to know (but I think there should be, though, because it's a good point). The only way I can think of right now is to treat 95%+ (or 99%+, if you want to be extra precise) with a combination of no power draw on batteries as your trigger.

Nothing for the first graph of today's production I succeeded perfectly but the second one with columns to understand I can't understand where the problem is

![Image](https://github.com/user-attachments/assets/ea7b70eb-68f1-4099-8faf-b7871e9d3990)

I tried to search for all these parameters in the status section of the developer tools but they don't exist, the last 2 are present as sensor.inverter_total_energy_import
sensor.inverter_total_energy_export
but the others are as if that parameter didn't exist. I'm interested in having the graph with only daily production, total daily consumption, battery charge and battery discharge, this is because I'm off grid but I can't understand how to solve it

**Comment by davidrapan** [comment]
It's just an example and these are my custom sensors (electricity prices). You need to supply them yourself.

**Comment by alex-military** [comment]
> È solo un esempio e questi sono i miei sensori personalizzati (prezzi dell'elettricità). Devi fornirli tu stesso.

yes yes I understood in fact I removed those relating to the price and I inserted those of production and consumption today but the problem is that nothing comes out of the graph I can't understand if I'm taking the wrong parameters.
in the end what I want to obtain is a replica of the column graph of the deye cloud app with the parameters daily production daily consumption daily battery charge and discharge. inserting this data does not bring out the graph. 😅 sorry if I don't understand but it's the first time I've used home assistant and so I'm trying to learn

**Comment by davidrapan** [comment]
This is the bar graph (slightly improved):
```
type: custom:plotly-graph
title: null
time_offset: 10h
hours_to_show: 8d
refresh_interval: 120
view_layout:
  grid-area: daily
layout:
  xaxis:
    showgrid: false
  yaxis:
    showgrid: false
    fixedrange: true
  legend:
    bgcolor: rgba(0,0,0,0)
    itemsizing: constant
    font:
      size: 12
  height: 450
config:
  displayModeBar: false
  scrollZoom: false
entities:
  - entity: sensor.inverter_total_energy_export
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "💰 " + "Export" + " (" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: "%{y}"
    filters:
      - filter: i>0
      - delta
    marker:
      color: rgb(162, 128, 219)
  - entity: sensor.inverter_total_energy_import
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "💡 " + "Import" + " (" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: "%{y}"
    filters:
      - filter: i>0
      - delta
    marker:
      color: rgb(84, 144, 194)
  - entity: sensor.inverter_total_production
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "☀️ " + "Solar" + " (" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: "%{y}"
    filters:
      - filter: i>0
      - delta
    marker:
      color: rgb(255, 152, 0)
  - entity: sensor.inverter_total_load_consumption
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "⚡ " + "Load" + " (" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    filters:
      - filter: i>0
      - delta
    texttemplate: "%{y}"
    marker:
      color: rgb(95, 182, 173)
  - entity: sensor.inverter_total_battery_charge
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "🔋 " + "Battery Charge" + " (" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: "%{y}"
    filters:
      - filter: i>0
      - delta
    marker:
      color: rgb(240, 98, 146)
  - entity: sensor.inverter_total_battery_discharge
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "🔋 " + "Battery Discharge" + " (" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: "%{y}"
    filters:
      - filter: i>0
      - delta
    marker:
      color: pink
```
