### ISSUE TITLE
TOU settings with ME3000SP

### ISSUE THREAD

**Issue by PaulOckenden** [davidrapan/ha-solarman#85]
I have 2 x ME3000SP battery controller/inverters, both using WiFi stick loggers and the sofar_wifikit.yaml definitions.

I’d *love* to be able to switch the working mode between auto and TOU if possible, and icing on the cake would be to adjust the main TOU parameters. There’s several TOU ‘slots’ available, but I’d be happy just to be able to set the first one.

I think this must be possible, because sometimes Sofar enable the ability to change the settings from the app (although this facility seems to come and go). 

I realise I could do this by switching to passive/bypass mode and using an ESP32 and mqtt, and that might be more flexible, but it’s also one more thing that might go wrong. In the spirit of keeping things simple I’d like to explore the option of changing these settings using this integration. 

I’m out of my depth when it comes to the dev side, but I’d be happy to help test, if anyone is up for this. 

Thank you.

**Comment by davidrapan** [comment]
Hi @PaulOckenden,

This integration does support configuration of your device so it should be doable! The only thing needed are the registers which does contain those values and then they can be added into said profile!

So if you are able to somehow get this information I'm more than happy to help!

**Comment by PaulOckenden** [comment]
Now working - the register was 0x1200. 

Or 4608 in decimal.

Thanks.

**Comment by davidrapan** [comment]
Great. Do you want to add those registers as regular configurables? So they are directly exposed in the sensor list of the device?

**Comment by PaulOckenden** [comment]
Entirely up to you. I'm happy specifying the number, but if you want to take it to the next level that's fine by me!

**Comment by davidrapan** [comment]
So what profile it is and what are the possible values for the register then?

**Comment by PaulOckenden** [comment]
It's for sofar_wifikit.yaml, the register is 4608, the name is working_mode and the possible values are:
0 : auto
1 : time_of_use
2: timing
3: passive

It's read/write, but only works with write multiple.

**Comment by davidrapan** [comment]
```
      - name: Working Mode
        update_interval: 300
        platform: select
        rule: 1
        registers: [0x1200]
        options: ["Auto", "Time of Use", "Timing", "Passive"]
        lookup:
          - key: 0x0000
            value: "Auto"
          - key: 0x0001
            value: "Time of Use"
          - key: 0x0001
            value: "Timing"
          - key: 0x0001
            value: "Passive"
```

Try to add this into the profile and reload the integration. Report back if it works as expected. I'll add it if so. 😉
